"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { mostrarAvisoDialogo, pedirMotivoDialogo } from "@/components/Dialogo";
import { createClient } from "@/lib/supabase/client";
import estilos from "./Comercial.module.css";

type Resumen = { contratos:number; prendas:number; facturado:number; cobrado:number; saldo:number };
type Vendedor = Resumen & { vendedor:string; entregados:number; a_tiempo:number; comision_proyectada:number };
type Tienda = Resumen & { id:string|null; tienda:string };
type Canal = Resumen & { canal:string };
type Contrato = { id:string; numero:string; nombre_contrato:string; cliente:string; cliente_confirmado:boolean; vendedor:string; tienda:string; canal:string; fecha:string; entrega:string|null; prendas:number; facturado:number; cobrado:number; saldo:number; entregado:number; entrega_a_tiempo:boolean|null };
type Catalogos = { vendedores:string[]; almacenes:Array<{id:string;nombre:string}>; canales:string[] };
type Datos = { desde:string; hasta:string; kpis:{contratos:number;produccion_vendida:number;facturado:number;cobrado:number;saldo:number;entregados:number;a_tiempo:number;comision_futura:number;clientes_por_confirmar:number}; vendedores:Vendedor[];tiendas:Tienda[];canales:Canal[];catalogos:Catalogos;contratos:Contrato[] };
type Vista = "vendedores"|"tiendas"|"canales"|"contratos";

const USD = new Intl.NumberFormat("es-EC", { style:"currency", currency:"USD" });
const NUM = new Intl.NumberFormat("es-EC");
function isoLocal(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function inicioMes(){const d=new Date();d.setDate(1);return isoLocal(d)}
function hoy(){return isoLocal(new Date())}
const VACIO:Datos={desde:"",hasta:"",kpis:{contratos:0,produccion_vendida:0,facturado:0,cobrado:0,saldo:0,entregados:0,a_tiempo:0,comision_futura:0,clientes_por_confirmar:0},vendedores:[],tiendas:[],canales:[],catalogos:{vendedores:[],almacenes:[],canales:[]},contratos:[]};

export default function ConsolidadoComercialCliente({puedeConfigurarComisiones}:{puedeConfigurarComisiones:boolean}){
 const supabase=createClient();
 const[datos,setDatos]=useState<Datos>(VACIO);const[cargando,setCargando]=useState(false);const[vista,setVista]=useState<Vista>("vendedores");
 const[filtros,setFiltros]=useState({desde:inicioMes(),hasta:hoy(),vendedores:[] as string[],almacenes:[] as string[],canales:[] as string[]});
 const[comision,setComision]=useState({vendedor:"",porcentaje:"",base:"cobrado",desde:hoy(),hasta:"",nota:""});const[guardando,setGuardando]=useState(false);
 const cargar=useCallback(async()=>{setCargando(true);const{data,error}=await supabase.rpc("consolidado_comercial_v115",{p_desde:filtros.desde,p_hasta:filtros.hasta,p_vendedores:filtros.vendedores.length?filtros.vendedores:null,p_almacenes:filtros.almacenes.length?filtros.almacenes:null,p_canales:filtros.canales.length?filtros.canales:null});setCargando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo cargar el consolidado",true);setDatos(data as Datos)},[filtros,supabase]);
 useEffect(()=>{void cargar()},[cargar]);
 const cumplimiento=datos.kpis.entregados?Math.round(datos.kpis.a_tiempo/datos.kpis.entregados*100):0;
 const cobro=datos.kpis.facturado?Math.round(datos.kpis.cobrado/datos.kpis.facturado*100):0;
 const maxVendedor=useMemo(()=>Math.max(1,...datos.vendedores.map(x=>Number(x.facturado))),[datos.vendedores]);
 async function guardarComision(){if(!comision.vendedor||comision.porcentaje===""||Number(comision.porcentaje)<0||Number(comision.porcentaje)>100)return mostrarAvisoDialogo("Selecciona un vendedor y escribe un porcentaje entre 0 y 100.","Datos incompletos",true);const motivo=await pedirMotivoDialogo(`Explica por qué se configura una comisión de ${comision.porcentaje}% para ${comision.vendedor}.`,10,"Motivo de la comisión");if(!motivo)return;setGuardando(true);const{error}=await supabase.rpc("guardar_comision_vendedor_v115",{p_vendedor:comision.vendedor,p_porcentaje:Number(comision.porcentaje),p_base:comision.base,p_vigente_desde:comision.desde,p_vigente_hasta:comision.hasta||null,p_nota:comision.nota||null,p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});setGuardando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo guardar la comisión",true);await mostrarAvisoDialogo("La regla de comisión quedó guardada y auditada.","Comisión actualizada");await cargar()}
 return <>
  <header className={estilos.cabecera}><div><span className="eyebrow">ANÁLISIS · v115</span><h1>Consolidado comercial</h1><p>Ventas, producción, cumplimiento, cobros y comisiones en una sola vista.</p></div><button className="secondary" onClick={()=>void cargar()} disabled={cargando}>{cargando?"Actualizando…":"Actualizar"}</button></header>
  <section className={`card ${estilos.filtros}`}>
   <div className="field"><label>Desde</label><input type="date" value={filtros.desde} onChange={e=>setFiltros({...filtros,desde:e.target.value})}/></div>
   <div className="field"><label>Hasta</label><input type="date" value={filtros.hasta} onChange={e=>setFiltros({...filtros,hasta:e.target.value})}/></div>
   <SelectorMultiple titulo="Vendedores" opciones={datos.catalogos.vendedores.map(x=>({valor:x,etiqueta:x}))} seleccion={filtros.vendedores} cambiar={vendedores=>setFiltros({...filtros,vendedores})}/>
   <SelectorMultiple titulo="Tiendas" opciones={datos.catalogos.almacenes.map(x=>({valor:x.id,etiqueta:x.nombre}))} seleccion={filtros.almacenes} cambiar={almacenes=>setFiltros({...filtros,almacenes})}/>
   <SelectorMultiple titulo="Canales" opciones={datos.catalogos.canales.map(x=>({valor:x,etiqueta:x}))} seleccion={filtros.canales} cambiar={canales=>setFiltros({...filtros,canales})}/>
   <button onClick={()=>void cargar()} disabled={cargando}>Aplicar</button><button className="secondary" onClick={()=>setFiltros({desde:inicioMes(),hasta:hoy(),vendedores:[],almacenes:[],canales:[]})}>Limpiar</button>
  </section>
  {!!datos.kpis.clientes_por_confirmar&&<div className={estilos.aviso}><strong>{datos.kpis.clientes_por_confirmar} contrato(s) histórico(s)</strong> conservan el texto anterior como nombre de contrato. El cliente real queda marcado como pendiente de confirmar.</div>}
  <section className={estilos.kpis}>
   <Kpi titulo="Ventas" valor={NUM.format(datos.kpis.contratos)} detalle={`${NUM.format(datos.kpis.produccion_vendida)} prendas`}/><Kpi titulo="Facturado" valor={USD.format(datos.kpis.facturado)} detalle={`${cobro}% cobrado`}/><Kpi titulo="Cobrado" valor={USD.format(datos.kpis.cobrado)} detalle={`Saldo ${USD.format(datos.kpis.saldo)}`}/><Kpi titulo="Entregas a tiempo" valor={`${cumplimiento}%`} detalle={`${datos.kpis.a_tiempo} de ${datos.kpis.entregados} completas`}/><Kpi titulo="Comisiones futuras" valor={USD.format(datos.kpis.comision_futura)} detalle="Proyección según reglas vigentes"/>
  </section>
  <section className="card">
   <nav className={estilos.tabs}>{([['vendedores','Por vendedor'],['tiendas','Por tienda'],['canales','Por canal'],['contratos','Detalle de contratos']] as [Vista,string][]).map(([id,t])=><button key={id} className={vista===id?estilos.activa:"secondary"} onClick={()=>setVista(id)}>{t}</button>)}</nav>
   {cargando?<div className={estilos.vacio}>Preparando indicadores…</div>:vista==="vendedores"?<TablaVendedores filas={datos.vendedores} max={maxVendedor}/>:vista==="tiendas"?<TablaResumen filas={datos.tiendas} clave="tienda"/>:vista==="canales"?<TablaResumen filas={datos.canales} clave="canal"/>:<TablaContratos filas={datos.contratos}/>} 
  </section>
  {puedeConfigurarComisiones&&<section className={`card ${estilos.comisiones}`}><div><span className="eyebrow">CONFIGURACIÓN</span><h2>Comisiones futuras</h2><p>La proyección puede calcularse sobre lo facturado o únicamente sobre lo cobrado.</p></div><div className={estilos.formComision}><div className="field"><label>Vendedor</label><select value={comision.vendedor} onChange={e=>setComision({...comision,vendedor:e.target.value})}><option value="">Seleccionar…</option>{datos.catalogos.vendedores.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Porcentaje</label><input type="number" min="0" max="100" step="0.01" value={comision.porcentaje} onChange={e=>setComision({...comision,porcentaje:e.target.value})}/></div><div className="field"><label>Base</label><select value={comision.base} onChange={e=>setComision({...comision,base:e.target.value})}><option value="cobrado">Cobrado</option><option value="facturado">Facturado</option></select></div><div className="field"><label>Vigente desde</label><input type="date" value={comision.desde} onChange={e=>setComision({...comision,desde:e.target.value})}/></div><div className="field"><label>Hasta (opcional)</label><input type="date" value={comision.hasta} onChange={e=>setComision({...comision,hasta:e.target.value})}/></div><div className="field"><label>Nota</label><input value={comision.nota} onChange={e=>setComision({...comision,nota:e.target.value})}/></div><button onClick={()=>void guardarComision()} disabled={guardando}>{guardando?"Guardando…":"Guardar regla"}</button></div></section>}
 </>;
}

function Kpi({titulo,valor,detalle}:{titulo:string;valor:string;detalle:string}){return <article><span>{titulo}</span><strong>{valor}</strong><small>{detalle}</small></article>}
function SelectorMultiple({titulo,opciones,seleccion,cambiar}:{titulo:string;opciones:Array<{valor:string;etiqueta:string}>;seleccion:string[];cambiar:(x:string[])=>void}){function alternar(valor:string){cambiar(seleccion.includes(valor)?seleccion.filter(x=>x!==valor):[...seleccion,valor])}return <div className={estilos.selector}><label>{titulo}</label><details><summary>{seleccion.length?`${seleccion.length} seleccionado(s)`:"Todos"}</summary><div>{opciones.map(x=><label key={x.valor}><input type="checkbox" checked={seleccion.includes(x.valor)} onChange={()=>alternar(x.valor)}/><span>{x.etiqueta}</span></label>)}{!opciones.length&&<small>Sin opciones</small>}</div></details></div>}
function TablaVendedores({filas,max}:{filas:Vendedor[];max:number}){return <div className="tabla-scroll"><table><thead><tr><th>Vendedor</th><th className="num">Contratos</th><th className="num">Prendas</th><th className="num">Facturado</th><th className="num">Cobrado</th><th>Cumplimiento</th><th className="num">Comisión futura</th></tr></thead><tbody>{filas.map(x=>{const pct=x.entregados?Math.round(x.a_tiempo/x.entregados*100):0;return <tr key={x.vendedor}><td><strong>{x.vendedor}</strong><div className={estilos.barra}><i style={{width:`${Number(x.facturado)/max*100}%`}}/></div></td><td className="num">{x.contratos}</td><td className="num">{x.prendas}</td><td className="num">{USD.format(x.facturado)}</td><td className="num">{USD.format(x.cobrado)}</td><td><span className={`badge ${pct>=90?"ok":pct>=70?"warning":"error"}`}>{pct}%</span><small>{x.a_tiempo}/{x.entregados}</small></td><td className="num"><strong>{USD.format(x.comision_proyectada||0)}</strong></td></tr>})}</tbody></table>{!filas.length&&<div className={estilos.vacio}>No hay ventas en este rango.</div>}</div>}
function TablaResumen<T extends Tienda|Canal>({filas,clave}:{filas:T[];clave:"tienda"|"canal"}){return <div className="tabla-scroll"><table><thead><tr><th>{clave==="tienda"?"Tienda":"Canal"}</th><th className="num">Contratos</th><th className="num">Prendas</th><th className="num">Facturado</th><th className="num">Cobrado</th><th className="num">Saldo</th></tr></thead><tbody>{filas.map((x,i)=><tr key={`${String(x[clave as keyof T])}-${i}`}><td><strong>{String(x[clave as keyof T])}</strong></td><td className="num">{x.contratos}</td><td className="num">{x.prendas}</td><td className="num">{USD.format(x.facturado)}</td><td className="num">{USD.format(x.cobrado)}</td><td className="num">{USD.format(x.saldo)}</td></tr>)}</tbody></table>{!filas.length&&<div className={estilos.vacio}>No hay datos para mostrar.</div>}</div>}
function TablaContratos({filas}:{filas:Contrato[]}){return <div className="tabla-scroll"><table><thead><tr><th>Contrato / cliente</th><th>Vendedor</th><th>Tienda / canal</th><th className="num">Prendas</th><th className="num">Facturado</th><th className="num">Cobrado</th><th>Entrega</th><th/></tr></thead><tbody>{filas.map(x=><tr key={x.id}><td><strong>{x.numero} · {x.nombre_contrato}</strong><div>{x.cliente}{!x.cliente_confirmado&&<span className="badge warning">Por confirmar</span>}</div></td><td>{x.vendedor}</td><td>{x.tienda}<small>{x.canal}</small></td><td className="num">{x.prendas}</td><td className="num">{USD.format(x.facturado)}</td><td className="num">{USD.format(x.cobrado)}</td><td>{x.entrega_a_tiempo===null?<span className="badge">Pendiente</span>:x.entrega_a_tiempo?<span className="badge ok">A tiempo</span>:<span className="badge error">Tarde</span>}<small>{x.entregado}/{x.prendas} prendas</small></td><td><Link className="button secondary" href="/produccion/contratos">Abrir brief</Link></td></tr>)}</tbody></table>{!filas.length&&<div className={estilos.vacio}>No hay contratos en este rango.</div>}</div>}
