"use client";
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useRef, useState } from "react";
import { confirmarDialogo, mostrarAvisoDialogo } from "@/components/Dialogo";
import { createClient } from "@/lib/supabase/client";
import ExpedienteContrato, { type Expediente } from "./ExpedienteContrato";
import GestionContratoV99 from "./GestionContratoV99";
import estilos from "./Contratos.module.css";

type Fila={id:string;numero:string;cliente:string;vendedor:string;disenador:string|null;estado:string;prioridad:string;fecha_entrega:string|null;total_prendas:number;presupuesto:number;abono:number;saldo:number;mockup_drive_id:string|null};
type Lista={total:number;pagina:number;por_pagina:number;estados:string[];filas:Fila[]};
const VACIA:Lista={total:0,pagina:1,por_pagina:40,estados:[],filas:[]};
const POR_PAGINA=40;
const DINERO=new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"});
function fecha(v:string|null){if(!v)return"—";return new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`))}
function fechaHora(v:string){return new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Guayaquil"}).format(new Date(v))}

export default function ContratosCliente({puedeEditar}:{puedeEditar:boolean}){
 const supabase=useRef(createClient()).current;
 const [lista,setLista]=useState<Lista>(VACIA);const [busqueda,setBusqueda]=useState("");const [estado,setEstado]=useState("");const [aplicado,setAplicado]=useState({busqueda:"",estado:""});const [pagina,setPagina]=useState(1);const [cargando,setCargando]=useState(true);const [error,setError]=useState<string|null>(null);const [expediente,setExpediente]=useState<Expediente|null>(null);const [cargandoExp,setCargandoExp]=useState(false);const [enlace,setEnlace]=useState("");const [vigencia,setVigencia]=useState(7);const [editando,setEditando]=useState(false);
 const cargar=useCallback(async()=>{setCargando(true);setError(null);const{data,error}=await supabase.rpc("listar_contratos_v97",{p_busqueda:aplicado.busqueda||null,p_estado:aplicado.estado||null,p_pagina:pagina,p_por_pagina:POR_PAGINA});if(error)setError(error.message.includes("listar_contratos_v97")?"Falta instalar v97 en Supabase.":error.message);else setLista(data as Lista);setCargando(false)},[aplicado,pagina,supabase]);
 useEffect(()=>{void cargar()},[cargar]);
 async function abrir(id:string){setCargandoExp(true);setEnlace("");const{data,error}=await supabase.rpc("obtener_expediente_contrato_v97",{p_contrato_id:id});if(error)await mostrarAvisoDialogo(error.message,"No se pudo abrir el expediente",true);else{setExpediente(data as Expediente);setTimeout(()=>document.getElementById("expediente-v97")?.scrollIntoView({behavior:"smooth",block:"start"}),50)}setCargandoExp(false)}
 async function refrescarGestion(){if(!expediente)return;await abrir(expediente.contrato.id);await cargar()}
 async function compartir(){if(!expediente)return;const{data,error}=await supabase.rpc("crear_enlace_brief_v97",{p_contrato_id:expediente.contrato.id,p_dias_vigencia:vigencia});if(error)return mostrarAvisoDialogo(error.message,"No se pudo crear el enlace",true);const url=`${window.location.origin}/brief/${data.token}`;await abrir(expediente.contrato.id);setEnlace(url)}
 async function copiar(){try{await navigator.clipboard.writeText(enlace);await mostrarAvisoDialogo("El enlace fue copiado al portapapeles.","Enlace copiado")}catch{await mostrarAvisoDialogo("No se pudo copiar automáticamente. Selecciona el enlace y cópialo.","Copia manual")}}
 async function revocar(id:string){if(!await confirmarDialogo("El brief dejará de abrir inmediatamente. ¿Deseas revocar este enlace?",true))return;const{error}=await supabase.rpc("revocar_enlace_brief_v97",{p_enlace_id:id});if(error)return mostrarAvisoDialogo(error.message,"No se pudo revocar",true);if(expediente)await abrir(expediente.contrato.id)}
 const totalPag=Math.max(1,Math.ceil(lista.total/POR_PAGINA));
 return <>
  <header className={estilos.cabecera}><div><span className="eyebrow">PRODUCCIÓN</span><h1>Expedientes de contratos</h1><p>Brief técnico, prendas, jugadores, diseños, facturación y trazabilidad en un solo lugar.</p></div></header>
  <section className={`card ${estilos.noImprimir}`}><div className={estilos.filtros}><div className="field"><label>Buscar contrato</label><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setPagina(1);setAplicado({busqueda,estado})}}} placeholder="Número, cliente, vendedor o diseñador"/></div><div className="field"><label>Estado</label><select value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos</option>{lista.estados.map(x=><option key={x}>{x}</option>)}</select></div><button onClick={()=>{setPagina(1);setAplicado({busqueda,estado})}}>Buscar</button></div></section>
  {error&&<div className="error-box">{error}</div>}
  <section className="card"><div className="header-row"><h2 style={{margin:0}}>Contratos</h2><span className="conteo">{lista.total} expediente(s)</span></div>{cargando?<div className={estilos.vacio}>Cargando contratos…</div>:<div className="tabla-scroll"><table><thead><tr><th>Contrato</th><th>Estado</th><th>Entrega</th><th>Diseño</th><th className="num">Prendas</th><th className="num">Saldo</th><th></th></tr></thead><tbody>{lista.filas.map(x=><tr key={x.id}><td><div className={estilos.contrato}>{x.mockup_drive_id&&<img className={estilos.miniatura} src={`https://drive.google.com/thumbnail?id=${x.mockup_drive_id}&sz=w180`} alt="" loading="lazy"/>}<div><strong>{x.prioridad==="Urgente"?"● ":""}{x.numero}</strong><span>{x.cliente}</span><small>{x.vendedor||"Sin vendedor"}</small></div></div></td><td><span className="badge ok">{x.estado}</span></td><td>{fecha(x.fecha_entrega)}</td><td>{x.disenador||<span className="conteo">Sin asignar</span>}</td><td className="num">{x.total_prendas}</td><td className="num"><strong>{DINERO.format(x.saldo)}</strong></td><td><button className="secondary" disabled={cargandoExp} onClick={()=>{setEditando(false);void abrir(x.id)}}>Abrir expediente</button></td></tr>)}{!lista.filas.length&&<tr><td colSpan={7} className={estilos.vacio}>No hay contratos con ese criterio.</td></tr>}</tbody></table></div>}{totalPag>1&&<div className={estilos.paginacion}><button className="secondary" disabled={pagina===1} onClick={()=>setPagina(x=>x-1)}>Anterior</button><span>Página {pagina} de {totalPag}</span><button className="secondary" disabled={pagina===totalPag} onClick={()=>setPagina(x=>x+1)}>Siguiente</button></div>}</section>
  {expediente&&<section id="expediente-v97">
   <div className={`${estilos.barraExpediente} ${estilos.noImprimir}`}><div><h2>{expediente.contrato.numero}</h2><span className="conteo">Expediente actualizado {fechaHora(expediente.contrato.updated_at)}</span></div><div className={estilos.acciones}>{puedeEditar&&<button onClick={()=>setEditando(x=>!x)}>{editando?"Ocultar gestión":"Editar gestión"}</button>}<select value={vigencia} onChange={e=>setVigencia(Number(e.target.value))} aria-label="Vigencia del enlace"><option value={1}>1 día</option><option value={7}>7 días</option><option value={15}>15 días</option><option value={30}>30 días</option></select><button className="secondary" onClick={compartir}>Crear enlace</button><button className="secondary" onClick={()=>window.print()}>Imprimir brief</button><button onClick={()=>{setExpediente(null);setEnlace("");setEditando(false)}}>Cerrar</button></div></div>
   {editando&&puedeEditar&&<GestionContratoV99 contrato={expediente.contrato as Record<string,unknown>&{id:string;numero:string}} onGuardado={refrescarGestion} onCerrar={()=>setEditando(false)}/>}
   {enlace&&<div className={`card ${estilos.noImprimir}`}><strong>Enlace temporal listo</strong><div className={estilos.enlace}><input readOnly value={enlace} onFocus={e=>e.target.select()}/><button onClick={copiar}>Copiar</button></div></div>}
   <ExpedienteContrato datos={expediente}/>
   {(expediente.enlaces||[]).length>0&&<section className={`card ${estilos.noImprimir}`}><h3>Enlaces compartidos</h3><div className={estilos.enlacesActivos}>{expediente.enlaces!.map(x=><div className={estilos.enlaceActivo} key={x.id}><span>{x.vigente?"Vigente":"Cerrado"} · vence {fechaHora(x.vence_en)}</span>{x.vigente&&<button className="secondary btn-mini" onClick={()=>revocar(x.id)}>Revocar</button>}</div>)}</div></section>}
  </section>}
 </>;
}
