"use client";

import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { confirmarDialogo, mostrarAvisoDialogo } from "@/components/Dialogo";
import { createClient } from "@/lib/supabase/client";
import type { Perfil } from "@/lib/permisos";
import estilos from "./IngresoContrato.module.css";

const PASOS=["Cliente","Contrato","Prendas","Diseños","Técnica","Jugadores","Cierre"];
const PRENDAS=["Camiseta Jugador","Camiseta Jugador M/L","Pantaloneta Jugador","Camiseta Arquero","Camiseta Arquero M/L","Pantaloneta Arquero","Camiseta Polo","Camiseta Polo M/L","Chompa","Pantalón","Rompevientos","Chompa de Frío","Chompa Frío 3/4","Chompas Retro","Chompa Deportiva","Hoodie","Buzo de Compresión","Chaleco","Bermudas","Falda Short","Licra","Bolsos","BVDS","Medias","Bandera","Cinta Capitán"];
const CALIDADES=["Amateur","Semi profesional","Profesional","Competición","Sin calidad"];
const ADULTOS=["XS","S","M","L","XL","2XL","3XL","4XL"];
const NINOS=["24 (0)","26 (2)","28 (4)","30 (6)","32 (8)","34 (10)","36 (12)"];
const TECNICAS=["Sublimado","Estampado","Bordado","TPU","No aplica"];
const BORRADOR="boman-contrato-v108-borrador";
const uuid=()=>crypto.randomUUID();

type Prenda={id:string;prenda:string;calidad:string;detalle:string;genero:"H"|"M"|"N";talla:string;cantidad:number};
type Jugador={id:string;nombre:string;numero:string;categoria:string;talla_superior:string;talla_inferior:string;manga:string;calidad:string;modelo_arquero:string;tipo_uniforme:string;detalle:string;mockup:string};
type Archivo={id:string;tipo:"mockup"|"logo";file?:File;preview?:string;url?:string;drive_id?:string;descripcion:string;color:string;prenda:string;posicion:string;tecnica:string;calidad_aplicable:string;observacion:string};
type Spec={id:string;prenda_clave:string;variante_calidad:string;indicaciones:string};
type Fact={id:string;concepto:string;calidad:string;cantidad:number;obsequio:boolean};
type Cab={vendedor:string;canal:string;cliente:string;telefono:string;whatsapp:string;email:string;tipo_contrato:string;fecha_entrega:string;fecha_inicio_produccion:string;prioridad:string;arqueros:number;reposicion:boolean;contrato_origen_reposicion_id:string;nombre_tecnica:string;numero_tecnica:string;sellos_tpu:string;ubicacion_tpu:string;bordado:string;colores:string;instrucciones:string;presupuesto:number;abono:number;forma_entrega:string;direccion:string;vendedor_responsable:string;autorizado:boolean;adicionales:string};
type Form={cab:Cab;prendas:Prenda[];jugadores:Jugador[];archivos:Archivo[];specs:Spec[];facturacion:Fact[]};

const cabInicial=(nombre:string):Cab=>({vendedor:nombre,canal:"Venta directa",cliente:"",telefono:"",whatsapp:"",email:"",tipo_contrato:"Normal",fecha_entrega:"",fecha_inicio_produccion:"",prioridad:"Normal",arqueros:0,reposicion:false,contrato_origen_reposicion_id:"",nombre_tecnica:"",numero_tecnica:"",sellos_tpu:"No",ubicacion_tpu:"",bordado:"",colores:"",instrucciones:"",presupuesto:0,abono:0,forma_entrega:"Retiro en tienda",direccion:"",vendedor_responsable:nombre,autorizado:false,adicionales:""});
const inicial=(nombre:string):Form=>({cab:cabInicial(nombre),prendas:[],jugadores:[],archivos:[],specs:[],facturacion:[]});
const texto=(v:unknown)=>String(v??"").trim();
function Campo({titulo,children,ancho=false}:{titulo:string;children:ReactNode;ancho?:boolean}){return <label className={ancho?estilos.ancho:""}><span>{titulo}</span>{children}</label>}

export default function IngresoContratoCliente({perfil}:{perfil:Perfil}){
 const supabase=useRef(createClient()).current;
 const [form,setForm]=useState<Form>(()=>inicial(perfil.nombre_completo));
 const [paso,setPaso]=useState(0); const [guardando,setGuardando]=useState(false); const [resultado,setResultado]=useState<{numero:string;id:string;respaldo:"en_curso"|"ok"|"pendiente"}|null>(null);
 const [busqueda,setBusqueda]=useState(""); const [coincidencias,setCoincidencias]=useState<any[]>([]); const [buscando,setBuscando]=useState(false); const [preview,setPreview]=useState(false);
 const total=useMemo(()=>form.prendas.reduce((s,x)=>s+Math.max(0,Number(x.cantidad)||0),0),[form.prendas]);
 const saldo=Math.max(0,Number(form.cab.presupuesto||0)-Number(form.cab.abono||0));
 const setCab=<K extends keyof Cab>(k:K,v:Cab[K])=>setForm(f=>({...f,cab:{...f.cab,[k]:v}}));
 const cambiar=<T extends {id:string}>(lista:keyof Pick<Form,"prendas"|"jugadores"|"archivos"|"specs"|"facturacion">,id:string,cambio:Partial<T>)=>setForm(f=>({...f,[lista]:(f[lista] as unknown as T[]).map(x=>x.id===id?{...x,...cambio}:x)} as Form));
 const quitar=(lista:keyof Pick<Form,"prendas"|"jugadores"|"archivos"|"specs"|"facturacion">,id:string)=>setForm(f=>({...f,[lista]:(f[lista] as {id:string}[]).filter(x=>x.id!==id)} as Form));

 useEffect(()=>{const raw=localStorage.getItem(BORRADOR);if(!raw)return;try{const d=JSON.parse(raw) as Form;if(d?.cab&&Array.isArray(d.prendas))void confirmarDialogo("Hay un borrador guardado en este dispositivo. ¿Deseas recuperarlo?").then(si=>si?setForm({...d,archivos:(d.archivos||[]).filter(x=>x.url)}):localStorage.removeItem(BORRADOR))}catch{localStorage.removeItem(BORRADOR)}},[]);
 useEffect(()=>{const t=setTimeout(()=>{const seguro={...form,archivos:form.archivos.filter(x=>x.url).map(({file,preview,...x})=>x)};localStorage.setItem(BORRADOR,JSON.stringify(seguro))},900);return()=>clearTimeout(t)},[form]);

 function errorPaso(n=paso){const c=form.cab;if(n===0&&(!texto(c.vendedor)||!texto(c.cliente)))return"Completa vendedor y cliente/equipo.";if(n===1&&(!c.fecha_entrega||!c.tipo_contrato||!c.prioridad))return"Completa tipo, prioridad y fecha de entrega.";if(n===2&&(!form.prendas.length||total<1))return"Agrega al menos una prenda con talla y cantidad.";if(n===4&&(!c.nombre_tecnica||!c.numero_tecnica||!c.sellos_tpu))return"Completa las técnicas de nombre, número y TPU.";if(n===6&&(!texto(c.vendedor_responsable)||!c.autorizado))return"Confirma el vendedor responsable y la autorización de producción.";if(n===6&&Number(c.abono)>Number(c.presupuesto))return"El abono no puede superar el presupuesto.";return""}
 async function irSiguiente(){const e=errorPaso();if(e)return mostrarAvisoDialogo(e,"Revisa este paso",true);setPaso(x=>Math.min(6,x+1))}
 async function abrirPaso(i:number){if(i>paso){const e=errorPaso();if(e)return mostrarAvisoDialogo(e,"Revisa este paso",true)}setPaso(i)}

 async function buscarAnterior(){if(texto(busqueda).length<2)return mostrarAvisoDialogo("Escribe al menos 2 caracteres.","Buscar reposición");setBuscando(true);const{data,error}=await supabase.rpc("buscar_contratos_reposicion_v108",{p_busqueda:busqueda});setBuscando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo buscar",true);setCoincidencias((data as any[])||[])}
 async function cargarReposicion(id:string){const{data,error}=await supabase.rpc("obtener_plantilla_contrato_v108",{p_contrato_id:id});if(error)return mostrarAvisoDialogo(error.message,"No se pudo cargar",true);const d:any=data,c=d.contrato||{};setForm(f=>({...f,cab:{...f.cab,tipo_contrato:c.tipo_contrato||"Normal",prioridad:c.prioridad||"Normal",reposicion:true,contrato_origen_reposicion_id:id,nombre_tecnica:c.nombre_tecnica||"",numero_tecnica:c.numero_tecnica||"",sellos_tpu:c.sellos_tpu||"No",ubicacion_tpu:c.ubicacion_tpu||"",bordado:c.bordado||"",colores:Array.isArray(c.colores_generales)?c.colores_generales.map((x:any)=>x.nombre||x).join(", "):"",adicionales:c.adicionales?.detalle||""},prendas:(d.prendas||[]).map((x:any)=>({...x,id:uuid()})),jugadores:(d.jugadores||[]).map((x:any)=>({...x,id:uuid()})),archivos:(d.archivos||[]).map((x:any)=>({...x,id:uuid()})),specs:(d.especificaciones||[]).map((x:any)=>({id:uuid(),prenda_clave:x.prenda_clave,variante_calidad:x.variante_calidad||"",indicaciones:x.spec?.indicaciones||JSON.stringify(x.spec)})),facturacion:(d.facturacion||[]).map((x:any)=>({...x,id:uuid()}))}));setBusqueda("");setCoincidencias([]);await mostrarAvisoDialogo("Se copiaron prendas, jugadores, diseños y especificaciones. Cliente, fechas y valores siguen siendo los del nuevo contrato.","Reposición preparada")}

 function agregarPrenda(){setForm(f=>({...f,prendas:[...f.prendas,{id:uuid(),prenda:"Camiseta Jugador",calidad:"Amateur",detalle:"",genero:"H",talla:"M",cantidad:1}]}))}
 function agregarJugador(){setForm(f=>({...f,jugadores:[...f.jugadores,{id:uuid(),nombre:"",numero:"",categoria:"Hombre",talla_superior:"M",talla_inferior:"M",manga:"Corta",calidad:"Amateur",modelo_arquero:"",tipo_uniforme:"Uniforme completo",detalle:"",mockup:""}]}))}
 function agregarSpec(){setForm(f=>({...f,specs:[...f.specs,{id:uuid(),prenda_clave:f.prendas[0]?.prenda||"Camiseta Jugador",variante_calidad:f.prendas[0]?.calidad||"Amateur",indicaciones:""}]}))}
 function agregarFact(){setForm(f=>({...f,facturacion:[...f.facturacion,{id:uuid(),concepto:"Uniforme completo",calidad:f.prendas[0]?.calidad||"Amateur",cantidad:1,obsequio:false}]}))}
 function seleccionar(tipo:"mockup"|"logo",files:FileList|null){if(!files)return;const limite=tipo==="mockup"?10:20;const nuevos=Array.from(files).slice(0,limite).map(file=>({id:uuid(),tipo,file,preview:file.type.startsWith("image/")?URL.createObjectURL(file):undefined,descripcion:file.name.replace(/\.[^.]+$/,""),color:"",prenda:"",posicion:"",tecnica:"",calidad_aplicable:"Todas",observacion:""}));setForm(f=>({...f,archivos:[...f.archivos,...nuevos]}))}

 async function importarJugadores(file:File){try{const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]],{defval:""});if(!rows.length)throw new Error("La hoja no contiene filas");const jugadores:Jugador[]=rows.map(r=>({id:uuid(),nombre:texto(r.Nombre||r.NOMBRE),numero:texto(r.Numero||r.Número||r.NUMERO),categoria:texto(r.Categoria||r.Categoría)||"Hombre",talla_superior:texto(r.Talla_superior||r["Talla camiseta"]),talla_inferior:texto(r.Talla_inferior||r["Talla pantaloneta"]),manga:texto(r.Manga)||"Corta",calidad:texto(r.Calidad)||"Amateur",modelo_arquero:texto(r.Modelo_arquero),tipo_uniforme:texto(r.Tipo_uniforme)||"Uniforme completo",detalle:texto(r.Detalle),mockup:texto(r.Mockup)}));setForm(f=>({...f,jugadores}));await mostrarAvisoDialogo(`Se cargaron ${jugadores.length} jugador(es).`,"Excel procesado")}catch(e){await mostrarAvisoDialogo(e instanceof Error?e.message:"No se pudo leer el archivo","Excel inválido",true)}}
 async function plantillaJugadores(){const XLSX=await import("xlsx");const ws=XLSX.utils.json_to_sheet([{Nombre:"",Numero:"",Categoria:"Hombre",Talla_superior:"M",Talla_inferior:"M",Manga:"Corta",Calidad:"Amateur",Modelo_arquero:"",Tipo_uniforme:"Uniforme completo",Detalle:"",Mockup:"Mockup 1"}]);ws["!cols"]=[24,10,14,16,16,12,18,18,24,28,16].map(wch=>({wch}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Jugadores");XLSX.writeFile(wb,"plantilla_jugadores_boman.xlsx")}

 async function guardar(){const falla=[0,1,2,4,6].map(errorPaso).find(Boolean);if(falla)return mostrarAvisoDialogo(falla,"Contrato incompleto",true);if(!await confirmarDialogo(`Se registrará un contrato nuevo con ${total} prendas y saldo de $${saldo.toFixed(2)}. ¿Continuar?`))return;setGuardando(true);try{const archivos:any[]=[];for(let orden=0;orden<form.archivos.length;orden++){const a=form.archivos[orden];if(!a.file){archivos.push({...a,orden});continue}const key=uuid();const prep=await supabase.rpc("preparar_archivo_contrato_v108",{p_nombre_archivo:a.file.name,p_mime_type:a.file.type,p_tamano_bytes:a.file.size,p_idempotency_key:key});if(prep.error)throw prep.error;const path=(prep.data as any).path;const subida=await supabase.storage.from("contratos-archivos").upload(path,a.file,{contentType:a.file.type,upsert:false});if(subida.error)throw subida.error;archivos.push({...a,file:undefined,preview:undefined,pendiente_id:(prep.data as any).id,url:supabase.storage.from("contratos-archivos").getPublicUrl(path).data.publicUrl,orden})}
  const mapa=new Map<string,Prenda>();for(const x of form.prendas){const k=[x.prenda,x.calidad,x.detalle,x.genero,x.talla].join("¦");const anterior=mapa.get(k);mapa.set(k,{...x,cantidad:(anterior?.cantidad||0)+Number(x.cantidad)})}
  const payload={contrato:{...form.cab,prendas_txt:Array.from(new Set(form.prendas.map(x=>x.prenda))).join(", "),colores_generales:form.cab.colores.split(",").map(x=>x.trim()).filter(Boolean).map(nombre=>({nombre})),adicionales:{detalle:form.cab.adicionales}},prendas:Array.from(mapa.values()).map(({id,...x})=>x),jugadores:form.jugadores.map(({id,...x},orden)=>({...x,orden})),archivos:archivos.map(({id,...x})=>x),especificaciones:form.specs.map(({id,indicaciones,...x},orden)=>({...x,orden,spec:{indicaciones}})),facturacion:form.facturacion.map(({id,...x},orden)=>({...x,orden}))};
  const alta=await supabase.rpc("crear_contrato_v108",{p_datos:payload,p_idempotency_key:uuid()});if(alta.error)throw alta.error;const r:any=alta.data;localStorage.removeItem(BORRADOR);setResultado({numero:r.numero,id:r.contrato_id,respaldo:"en_curso"});setPreview(false);void respaldar(r.contrato_id)}catch(e){await mostrarAvisoDialogo(e instanceof Error?e.message:"No se pudo registrar el contrato","Error al registrar",true)}finally{setGuardando(false)}}

 async function respaldar(id:string){try{const res=await fetch("/api/bomansport/respaldo-contrato",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contrato_id:id})});const data=await res.json();setResultado(x=>x&&x.id===id?{...x,respaldo:data.ok?"ok":"pendiente"}:x)}catch{setResultado(x=>x&&x.id===id?{...x,respaldo:"pendiente"}:x)}}

 if(resultado)return <section className={`card ${estilos.exito}`}><div>✓</div><h1>Contrato registrado</h1><strong>{resultado.numero}</strong><p>Ya está disponible en Producción → Contratos y en el tablero.</p><p className={resultado.respaldo==="pendiente"?estilos.respaldoPendiente:estilos.respaldoOk}>{resultado.respaldo==="en_curso"?"Respaldando en Google Sheets…":resultado.respaldo==="ok"?"✓ Copia de respaldo guardada en Google Sheets":"El respaldo en Sheets quedó pendiente; el contrato está seguro en Supabase."}</p><div>{resultado.respaldo==="pendiente"&&<button className="secondary" onClick={()=>void respaldar(resultado.id)}>Reintentar respaldo</button>}<button onClick={()=>{setResultado(null);setForm(inicial(perfil.nombre_completo));setPaso(0)}}>Ingresar otro</button><a className="button secondary" href="/produccion/contratos">Abrir expedientes</a></div></section>;
 return <>
  <header className={estilos.cabecera}><div><span className="eyebrow">VENTAS · v108</span><h1>Ingreso de contratos</h1><p>Pedido, brief técnico, tallas, diseños y valores conectados directamente con producción.</p></div><button className="secondary" onClick={()=>setPreview(true)}>Vista previa</button></header>
  <nav className={estilos.pasos}>{PASOS.map((x,i)=><button key={x} className={i===paso?estilos.activo:i<paso?estilos.completo:""} onClick={()=>void abrirPaso(i)}><b>{i<paso?"✓":i+1}</b><span>{x}</span></button>)}</nav>
  <section className={`card ${estilos.formulario}`}>
   {paso===0&&<PasoCliente form={form} setCab={setCab} busqueda={busqueda} setBusqueda={setBusqueda} buscar={buscarAnterior} buscando={buscando} coincidencias={coincidencias} cargar={cargarReposicion}/>} 
   {paso===1&&<PasoContrato form={form} setCab={setCab}/>} 
   {paso===2&&<PasoPrendas form={form} setForm={setForm} setCab={setCab} total={total} agregar={agregarPrenda} cambiar={cambiar} quitar={quitar}/>} 
   {paso===3&&<PasoArchivos form={form} seleccionar={seleccionar} cambiar={cambiar} quitar={quitar}/>} 
   {paso===4&&<PasoTecnica form={form} setCab={setCab} agregar={agregarSpec} cambiar={cambiar} quitar={quitar}/>} 
   {paso===5&&<PasoJugadores form={form} importar={importarJugadores} plantilla={plantillaJugadores} agregar={agregarJugador} cambiar={cambiar} quitar={quitar}/>} 
   {paso===6&&<PasoCierre form={form} setCab={setCab} saldo={saldo} agregar={agregarFact} cambiar={cambiar} quitar={quitar}/>} 
   <footer className={estilos.acciones}><button className="secondary" disabled={paso===0||guardando} onClick={()=>setPaso(x=>x-1)}>Anterior</button><span>Paso {paso+1} de 7 · borrador automático</span>{paso<6?<button onClick={()=>void irSiguiente()}>Continuar</button>:<><button className="secondary" onClick={()=>setPreview(true)}>Revisar</button><button onClick={()=>void guardar()} disabled={guardando}>{guardando?"Subiendo y registrando…":"Registrar contrato"}</button></>}</footer>
  </section>
  {preview&&<VistaPrevia form={form} total={total} saldo={saldo} cerrar={()=>setPreview(false)}/>} 
 </>;
}

type SetCab=<K extends keyof Cab>(k:K,v:Cab[K])=>void;
type Cambiar=<T extends {id:string}>(lista:keyof Pick<Form,"prendas"|"jugadores"|"archivos"|"specs"|"facturacion">,id:string,cambio:Partial<T>)=>void;
type Quitar=(lista:keyof Pick<Form,"prendas"|"jugadores"|"archivos"|"specs"|"facturacion">,id:string)=>void;

function PasoCliente({form,setCab,busqueda,setBusqueda,buscar,buscando,coincidencias,cargar}:{form:Form;setCab:SetCab;busqueda:string;setBusqueda:(x:string)=>void;buscar:()=>void;buscando:boolean;coincidencias:any[];cargar:(id:string)=>void}){return <><h2>Vendedor y cliente</h2><div className={estilos.reposicion}><div><strong>¿Es una reposición?</strong><span>Copia el brief anterior y crea un contrato nuevo.</span></div><div><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} onKeyDown={e=>e.key==="Enter"&&buscar()} placeholder="Cliente o BOM-2026-…"/><button className="secondary" onClick={buscar}>{buscando?"Buscando…":"Buscar"}</button></div>{coincidencias.map(x=><button className={estilos.resultado} key={x.id} onClick={()=>cargar(x.id)}><strong>{x.numero}</strong><span>{x.cliente} · {x.total_prendas} prendas</span></button>)}</div><div className={estilos.grid}><Campo titulo="Vendedor *"><input value={form.cab.vendedor} onChange={e=>setCab("vendedor",e.target.value)}/></Campo><Campo titulo="Canal"><select value={form.cab.canal} onChange={e=>setCab("canal",e.target.value)}><option>Venta directa</option><option>Tienda</option><option>WhatsApp</option><option>Redes sociales</option><option>Referido</option></select></Campo><Campo titulo="Cliente / equipo *"><input value={form.cab.cliente} onChange={e=>setCab("cliente",e.target.value)}/></Campo><Campo titulo="Teléfono"><input value={form.cab.telefono} onChange={e=>setCab("telefono",e.target.value)}/></Campo><Campo titulo="WhatsApp"><input value={form.cab.whatsapp} onChange={e=>setCab("whatsapp",e.target.value)}/></Campo><Campo titulo="Correo"><input type="email" value={form.cab.email} onChange={e=>setCab("email",e.target.value)}/></Campo></div></>}
function PasoContrato({form,setCab}:{form:Form;setCab:SetCab}){return <><h2>Tipo de contrato y fechas</h2><div className={estilos.tipos}>{[["Normal","600 prendas/día"],["Equipo Profesional","100 prendas/día"],["Mercadería","150 prendas/día"],["Emergente","50 prendas/día"]].map(x=><button className={form.cab.tipo_contrato===x[0]?estilos.seleccionado:""} onClick={()=>setCab("tipo_contrato",x[0])} key={x[0]}><strong>{x[0]}</strong><small>{x[1]}</small></button>)}</div><div className={estilos.grid}><Campo titulo="Fecha deseada por el cliente *"><input type="date" value={form.cab.fecha_entrega} onChange={e=>setCab("fecha_entrega",e.target.value)}/></Campo><Campo titulo="Inicio tentativo de producción"><input type="date" value={form.cab.fecha_inicio_produccion} onChange={e=>setCab("fecha_inicio_produccion",e.target.value)}/></Campo><Campo titulo="Prioridad *"><select value={form.cab.prioridad} onChange={e=>setCab("prioridad",e.target.value)}><option>Normal</option><option>Urgente</option></select></Campo></div></>}
function PasoPrendas({form,setCab,total,agregar,cambiar,quitar}:{form:Form;setForm:any;setCab:SetCab;total:number;agregar:()=>void;cambiar:Cambiar;quitar:Quitar}){return <><Titulo titulo="Prendas, calidades y tallas" texto="Cada fila representa una prenda, calidad, género y talla." accion={agregar} etiqueta="+ Agregar prenda"/>{form.prendas.map(x=><div className={estilos.filaPrenda} key={x.id}><select value={x.prenda} onChange={e=>cambiar<Prenda>("prendas",x.id,{prenda:e.target.value})}>{PRENDAS.map(p=><option key={p}>{p}</option>)}</select><select value={x.calidad} onChange={e=>cambiar<Prenda>("prendas",x.id,{calidad:e.target.value})}>{CALIDADES.map(p=><option key={p}>{p}</option>)}</select><input placeholder="Detalle" value={x.detalle} onChange={e=>cambiar<Prenda>("prendas",x.id,{detalle:e.target.value})}/><select value={x.genero} onChange={e=>cambiar<Prenda>("prendas",x.id,{genero:e.target.value as Prenda["genero"],talla:e.target.value==="N"?NINOS[0]:"M"})}><option value="H">Hombre</option><option value="M">Mujer</option><option value="N">Niño/a</option></select><select value={x.talla} onChange={e=>cambiar<Prenda>("prendas",x.id,{talla:e.target.value})}>{(x.genero==="N"?NINOS:ADULTOS).map(t=><option key={t}>{t}</option>)}</select><input type="number" min={1} value={x.cantidad} onChange={e=>cambiar<Prenda>("prendas",x.id,{cantidad:Number(e.target.value)})}/><button className="secondary" onClick={()=>quitar("prendas",x.id)}>Quitar</button></div>)}{!form.prendas.length&&<Vacio texto="Aún no agregas prendas."/>}<div className={estilos.total}>Total calculado <strong>{total}</strong></div><div className={estilos.grid}><Campo titulo="Cantidad de arqueros"><input type="number" min={0} value={form.cab.arqueros} onChange={e=>setCab("arqueros",Number(e.target.value))}/></Campo><Campo titulo="Adicionales del pedido" ancho><textarea rows={3} value={form.cab.adicionales} onChange={e=>setCab("adicionales",e.target.value)} placeholder="Medias, polainas, bandas, banderas, bolsos, medidas u otros…"/></Campo></div></>}
function PasoArchivos({form,seleccionar,cambiar,quitar}:{form:Form;seleccionar:(t:"mockup"|"logo",f:FileList|null)=>void;cambiar:Cambiar;quitar:Quitar}){return <><h2>Mockups, logos y sellos</h2><div className={estilos.cargas}><label><strong>Mockups</strong><span>Hasta 10 imágenes o PDF; el primero será principal.</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>seleccionar("mockup",e.target.files)}/></label><label><strong>Logos y sellos</strong><span>Puedes seleccionar varios archivos.</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>seleccionar("logo",e.target.files)}/></label></div><div className={estilos.archivos}>{form.archivos.map(a=><article key={a.id}>{a.preview?<img src={a.preview} alt=""/>:<div className={estilos.archivoViejo}>{a.tipo.toUpperCase()}</div>}<select value={a.tipo} onChange={e=>cambiar<Archivo>("archivos",a.id,{tipo:e.target.value as Archivo["tipo"]})}><option value="mockup">Mockup</option><option value="logo">Logo / sello</option></select><input value={a.descripcion} placeholder="Descripción" onChange={e=>cambiar<Archivo>("archivos",a.id,{descripcion:e.target.value})}/>{a.tipo==="logo"&&<><input value={a.prenda} placeholder="Prenda aplicable" onChange={e=>cambiar<Archivo>("archivos",a.id,{prenda:e.target.value})}/><input value={a.posicion} placeholder="Posición" onChange={e=>cambiar<Archivo>("archivos",a.id,{posicion:e.target.value})}/><input value={a.tecnica} placeholder="Técnica" onChange={e=>cambiar<Archivo>("archivos",a.id,{tecnica:e.target.value})}/></>}<button className="secondary" onClick={()=>quitar("archivos",a.id)}>Quitar</button></article>)}</div></>}
function PasoTecnica({form,setCab,agregar,cambiar,quitar}:{form:Form;setCab:SetCab;agregar:()=>void;cambiar:Cambiar;quitar:Quitar}){return <><h2>Especificaciones técnicas</h2><div className={estilos.grid}><Campo titulo="Nombre jugador - técnica *"><select value={form.cab.nombre_tecnica} onChange={e=>setCab("nombre_tecnica",e.target.value)}><option value="">Seleccionar…</option>{TECNICAS.map(x=><option key={x}>{x}</option>)}</select></Campo><Campo titulo="Número jugador - técnica *"><select value={form.cab.numero_tecnica} onChange={e=>setCab("numero_tecnica",e.target.value)}><option value="">Seleccionar…</option>{TECNICAS.map(x=><option key={x}>{x}</option>)}</select></Campo><Campo titulo="¿Lleva sellos TPU? *"><select value={form.cab.sellos_tpu} onChange={e=>setCab("sellos_tpu",e.target.value)}><option>No</option><option>Sí</option></select></Campo><Campo titulo="Ubicación TPU"><input value={form.cab.ubicacion_tpu} onChange={e=>setCab("ubicacion_tpu",e.target.value)}/></Campo><Campo titulo="Bordado / observaciones" ancho><textarea rows={3} value={form.cab.bordado} onChange={e=>setCab("bordado",e.target.value)}/></Campo><Campo titulo="Colores generales, separados por coma" ancho><input value={form.cab.colores} onChange={e=>setCab("colores",e.target.value)} placeholder="Azul marino, dorado, blanco"/></Campo></div><Titulo titulo="Detalle por prenda y calidad" accion={agregar} etiqueta="+ Especificación"/>{form.specs.map(s=><div className={estilos.filaSpec} key={s.id}><select value={s.prenda_clave} onChange={e=>cambiar<Spec>("specs",s.id,{prenda_clave:e.target.value})}>{Array.from(new Set(form.prendas.map(x=>x.prenda))).map(x=><option key={x}>{x}</option>)}</select><select value={s.variante_calidad} onChange={e=>cambiar<Spec>("specs",s.id,{variante_calidad:e.target.value})}>{CALIDADES.map(x=><option key={x}>{x}</option>)}</select><textarea value={s.indicaciones} onChange={e=>cambiar<Spec>("specs",s.id,{indicaciones:e.target.value})} placeholder="Cuello, puños, cierre, bolsillos, cortes, tela y acabados…"/><button className="secondary" onClick={()=>quitar("specs",s.id)}>Quitar</button></div>)}</>}
function PasoJugadores({form,importar,plantilla,agregar,cambiar,quitar}:{form:Form;importar:(f:File)=>void;plantilla:()=>void;agregar:()=>void;cambiar:Cambiar;quitar:Quitar}){return <><Titulo titulo="Jugadores y personalización" texto="Ingreso manual o carga desde Excel." accion={agregar} etiqueta="+ Jugador"><button className="secondary" onClick={plantilla}>Plantilla Excel</button><label className={estilos.botonArchivo}>Cargar Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&importar(e.target.files[0])}/></label></Titulo>{form.jugadores.map((j,i)=><div className={estilos.filaJugador} key={j.id}><b>{i+1}</b><input placeholder="Nombre" value={j.nombre} onChange={e=>cambiar<Jugador>("jugadores",j.id,{nombre:e.target.value})}/><input placeholder="Número" value={j.numero} onChange={e=>cambiar<Jugador>("jugadores",j.id,{numero:e.target.value})}/><select value={j.categoria} onChange={e=>cambiar<Jugador>("jugadores",j.id,{categoria:e.target.value})}><option>Hombre</option><option>Mujer</option><option>Niño</option><option>Niña</option></select><input placeholder="Talla sup." value={j.talla_superior} onChange={e=>cambiar<Jugador>("jugadores",j.id,{talla_superior:e.target.value})}/><input placeholder="Talla inf." value={j.talla_inferior} onChange={e=>cambiar<Jugador>("jugadores",j.id,{talla_inferior:e.target.value})}/><select value={j.calidad} onChange={e=>cambiar<Jugador>("jugadores",j.id,{calidad:e.target.value})}>{CALIDADES.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Detalle" value={j.detalle} onChange={e=>cambiar<Jugador>("jugadores",j.id,{detalle:e.target.value})}/><button className="secondary" onClick={()=>quitar("jugadores",j.id)}>Quitar</button></div>)}{!form.jugadores.length&&<Vacio texto="Este contrato no tiene nómina de jugadores."/>}</>}
function PasoCierre({form,setCab,saldo,agregar,cambiar,quitar}:{form:Form;setCab:SetCab;saldo:number;agregar:()=>void;cambiar:Cambiar;quitar:Quitar}){return <><h2>Producción, valores y cierre</h2><div className={estilos.grid}><Campo titulo="Presupuesto total (USD)"><input type="number" min={0} step=".01" value={form.cab.presupuesto} onChange={e=>setCab("presupuesto",Number(e.target.value))}/></Campo><Campo titulo="Abono recibido (USD)"><input type="number" min={0} step=".01" value={form.cab.abono} onChange={e=>setCab("abono",Number(e.target.value))}/></Campo><div className={estilos.saldo}><span>Saldo pendiente</span><strong>${saldo.toFixed(2)}</strong></div><Campo titulo="Forma de entrega"><select value={form.cab.forma_entrega} onChange={e=>setCab("forma_entrega",e.target.value)}><option>Retiro en tienda</option><option>Envío a domicilio</option><option>Courier</option><option>Entrega en cancha</option></select></Campo><Campo titulo="Dirección"><input value={form.cab.direccion} onChange={e=>setCab("direccion",e.target.value)}/></Campo><Campo titulo="Instrucciones especiales" ancho><textarea rows={4} value={form.cab.instrucciones} onChange={e=>setCab("instrucciones",e.target.value)}/></Campo><Campo titulo="Vendedor responsable *"><input value={form.cab.vendedor_responsable} onChange={e=>setCab("vendedor_responsable",e.target.value)}/></Campo></div><Titulo titulo="Detalle de facturación" accion={agregar} etiqueta="+ Línea"/>{form.facturacion.map(x=><div className={estilos.filaFact} key={x.id}><input value={x.concepto} onChange={e=>cambiar<Fact>("facturacion",x.id,{concepto:e.target.value})}/><select value={x.calidad} onChange={e=>cambiar<Fact>("facturacion",x.id,{calidad:e.target.value})}>{CALIDADES.map(x=><option key={x}>{x}</option>)}</select><input type="number" min={1} value={x.cantidad} onChange={e=>cambiar<Fact>("facturacion",x.id,{cantidad:Number(e.target.value)})}/><label className={estilos.check}><input type="checkbox" checked={x.obsequio} onChange={e=>cambiar<Fact>("facturacion",x.id,{obsequio:e.target.checked})}/> Obsequio</label><button className="secondary" onClick={()=>quitar("facturacion",x.id)}>Quitar</button></div>)}<label className={estilos.autoriza}><input type="checkbox" checked={form.cab.autorizado} onChange={e=>setCab("autorizado",e.target.checked)}/><span><strong>Confirmo que revisé todos los datos.</strong> Autorizo el envío de este contrato a producción.</span></label></>}
function Titulo({titulo,texto,accion,etiqueta,children}:{titulo:string;texto?:string;accion:()=>void;etiqueta:string;children?:ReactNode}){return <div className={estilos.tituloAccion}><div><h2>{titulo}</h2>{texto&&<p>{texto}</p>}</div><div>{children}<button onClick={accion}>{etiqueta}</button></div></div>}
function Vacio({texto}:{texto:string}){return <div className={estilos.vacio}>{texto}</div>}
function VistaPrevia({form,total,saldo,cerrar}:{form:Form;total:number;saldo:number;cerrar:()=>void}){return <div className={estilos.modal} onMouseDown={e=>e.target===e.currentTarget&&cerrar()}><article><header><div><span className="eyebrow">VISTA PREVIA</span><h2>{form.cab.cliente||"Contrato sin cliente"}</h2></div><button className="secondary" onClick={cerrar}>Cerrar</button></header><div className={estilos.resumen}><div><span>Vendedor</span><strong>{form.cab.vendedor||"—"}</strong></div><div><span>Entrega</span><strong>{form.cab.fecha_entrega||"—"}</strong></div><div><span>Tipo</span><strong>{form.cab.tipo_contrato}</strong></div><div><span>Total</span><strong>{total} prendas</strong></div></div><h3>Prendas</h3>{form.prendas.map(x=><p key={x.id}>{x.cantidad} × {x.prenda} · {x.calidad} · {x.genero}/{x.talla}</p>)}<h3>Producción</h3><p>{form.cab.instrucciones||"Sin instrucciones especiales."}</p><h3>Valores</h3><p>Presupuesto ${Number(form.cab.presupuesto).toFixed(2)} · Abono ${Number(form.cab.abono).toFixed(2)} · Saldo ${saldo.toFixed(2)}</p></article></div>}
