"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import ExpedienteContrato, { type Expediente } from "@/app/produccion/contratos/ExpedienteContrato";
import { mostrarAvisoDialogo, pedirMotivoDialogo } from "@/components/Dialogo";
import ImagenMockup from "@/components/ImagenMockup";
import { createClient } from "@/lib/supabase/client";
import estilos from "./Entregas.module.css";

type Fila = { id:string; numero:string; cliente:string; vendedor:string; vendedor_perfil_id:string|null; vendedor_usuario:string|null; estado:string; prioridad:string; fecha_entrega:string|null; total_prendas:number; entregadas:number; pendientes:number; presupuesto:number; abono:number; saldo:number; mockup_drive_id:string|null; mockup_url:string|null };
type Lista = { total:number; pagina:number; por_pagina:number; filas:Fila[] };
type Linea = { id:string; prenda:string; calidad:string; detalle:string; genero:string; talla:string; ordenadas:number; entregadas:number; pendientes:number };
type Archivo = { id:string; tipo:"foto"|"firma"|"comprobante"; storage_path:string; nombre_archivo:string; mime_type:string };
type Entrega = { id:string; secuencia:number; tipo:"parcial"|"completa"; estado:"aplicada"|"revertida"; fecha_entrega_real:string; responsable:string; observacion:string|null; creado_por:string; created_at:string; revertido_por:string|null; revertido_en:string|null; motivo_reversion:string|null; total:number; archivos:Archivo[] };
type Abono = { id:string; fecha:string; monto:number; medio_pago:string; referencia:string|null; nota:string|null; estado:string; created_at:string; creado_por:string|null };
type Finanzas = { presupuesto:number; abono_inicial:number; abonado:number; saldo:number; vendedor_perfil_id:string|null; vendedor_usuario:string|null };
type Detalle = { contrato:{id:string;numero:string;cliente:string;vendedor:string;estado:string;fecha_entrega:string|null;total_prendas:number}; lineas:Linea[]; entregas:Entrega[]; brief:Expediente; finanzas:Finanzas; abonos:Abono[] };
type Catalogo = { vendedores:{id:string;nombre:string;contratos:number}[]; origenes:{nombre:string;cantidad:number}[]; sin_asignar:number };
type Evidencia = { id:string; file:File; tipo:"foto"|"firma"|"comprobante" };

const VACIA:Lista={total:0,pagina:1,por_pagina:30,filas:[]}, CATALOGO_VACIO:Catalogo={vendedores:[],origenes:[],sin_asignar:0}, POR_PAGINA=30;
const DINERO=new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"});
function fecha(v:string|null){return v?new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${v.slice(0,10)}T12:00:00Z`)):"Sin fecha"}
function fechaHora(v:string){return new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Guayaquil"}).format(new Date(v))}
function ahoraLocal(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)}

export default function EntregasCliente({nombre,esVendedor,puedeEntregar,puedeRevertir,puedeAsignar}:{nombre:string;esVendedor:boolean;puedeEntregar:boolean;puedeRevertir:boolean;puedeAsignar:boolean}){
 const supabase=useRef(createClient()).current;
 const[lista,setLista]=useState<Lista>(VACIA),[catalogo,setCatalogo]=useState<Catalogo>(CATALOGO_VACIO);
 const[buscar,setBuscar]=useState(""),[aplicado,setAplicado]=useState(""),[soloSinAsignar,setSoloSinAsignar]=useState(false),[pagina,setPagina]=useState(1),[cargando,setCargando]=useState(true);
 const[detalle,setDetalle]=useState<Detalle|null>(null),[brief,setBrief]=useState<Expediente|null>(null),[cargandoDetalle,setCargandoDetalle]=useState<string|null>(null);
 const[origen,setOrigen]=useState(""),[vendedorDestino,setVendedorDestino]=useState(""),[vendedorDetalle,setVendedorDetalle]=useState(""),[asignando,setAsignando]=useState(false);
 const[cantidades,setCantidades]=useState<Record<string,string>>({}),[responsable,setResponsable]=useState(nombre),[fechaReal,setFechaReal]=useState(ahoraLocal()),[observacion,setObservacion]=useState("");
 const[evidencias,setEvidencias]=useState<Evidencia[]>([]),[guardando,setGuardando]=useState(false),[mensaje,setMensaje]=useState("");

 const cargar=useCallback(async()=>{setCargando(true);const{data,error}=await supabase.rpc("listar_centro_contratos_v158",{p_busqueda:aplicado||null,p_solo_sin_asignar:soloSinAsignar,p_pagina:pagina,p_por_pagina:POR_PAGINA});setCargando(false);if(error)return void mostrarAvisoDialogo(error.message,"No se pudieron cargar los contratos",true);setLista(data as Lista)},[aplicado,pagina,soloSinAsignar,supabase]);
 const cargarCatalogo=useCallback(async()=>{if(!puedeAsignar)return;const{data,error}=await supabase.rpc("catalogo_asignacion_vendedores_v158");if(error)return void mostrarAvisoDialogo(error.message,"No se pudo cargar la asignación",true);setCatalogo(data as Catalogo)},[puedeAsignar,supabase]);
 useEffect(()=>{void cargar()},[cargar]);useEffect(()=>{void cargarCatalogo()},[cargarCatalogo]);
 useEffect(()=>{const cerrar=(e:KeyboardEvent)=>{if(e.key==="Escape")setBrief(null)};document.addEventListener("keydown",cerrar);return()=>document.removeEventListener("keydown",cerrar)},[]);

 async function abrir(id:string){setCargandoDetalle(id);const{data,error}=await supabase.rpc("obtener_centro_contrato_v158",{p_contrato_id:id});setCargandoDetalle(null);if(error)return mostrarAvisoDialogo(error.message,"No se pudo abrir la ficha",true);const nuevo=data as Detalle;setDetalle(nuevo);setVendedorDetalle(nuevo.finanzas.vendedor_perfil_id||"");setCantidades({});setEvidencias([]);setResponsable(nombre);setFechaReal(ahoraLocal());setObservacion("");setMensaje("");setTimeout(()=>document.getElementById("detalle-entrega-v158")?.scrollIntoView({behavior:"smooth"}),40)}
 async function asignar(contratoId?:string){const destino=contratoId?vendedorDetalle:vendedorDestino;if(!destino||(!contratoId&&!origen))return mostrarAvisoDialogo("Selecciona el nombre importado y la cuenta del vendedor.","Asignación incompleta",true);const cantidad=contratoId?1:catalogo.origenes.find(x=>x.nombre===origen)?.cantidad||0,destinoNombre=catalogo.vendedores.find(x=>x.id===destino)?.nombre||"el vendedor";const motivo=await pedirMotivoDialogo(`Se vinculará${cantidad===1?"":"n"} ${cantidad} contrato${cantidad===1?"":"s"} con la cuenta de ${destinoNombre}. Así aparecerán en su usuario.`,10,contratoId?"Motivo de reasignación":"Motivo de asignación masiva");if(!motivo)return;setAsignando(true);const{data,error}=await supabase.rpc("asignar_vendedor_contratos_v158",{p_contrato_id:contratoId||null,p_vendedor_texto:contratoId?detalle?.contrato.vendedor||null:origen,p_vendedor_perfil_id:destino,p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});setAsignando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo asignar el vendedor",true);const r=data as{cantidad:number;vendedor:string};setOrigen("");setVendedorDestino("");await Promise.all([cargar(),cargarCatalogo()]);if(contratoId)await abrir(contratoId);await mostrarAvisoDialogo(`${r.cantidad} contrato(s) quedaron vinculados con ${r.vendedor}.`,"Vendedor asignado")}
 function completar(){if(detalle)setCantidades(Object.fromEntries(detalle.lineas.filter(x=>x.pendientes>0).map(x=>[x.id,String(x.pendientes)])))}
 async function agregar(files:FileList|null){if(!files)return;const permitidos=["image/jpeg","image/png","image/webp","application/pdf"],nuevos:Evidencia[]=[];for(const file of Array.from(files)){if(!permitidos.includes(file.type)||file.size<=0||file.size>12582912){await mostrarAvisoDialogo(`${file.name}: usa JPG, PNG, WebP o PDF de máximo 12 MB.`,"Evidencia no válida",true);continue}nuevos.push({id:crypto.randomUUID(),file,tipo:file.type==="application/pdf"?"comprobante":"foto"})}setEvidencias(x=>[...x,...nuevos])}
 async function guardar(){if(!detalle)return;const lineas=detalle.lineas.map(x=>({contrato_prenda_id:x.id,cantidad:Number(cantidades[x.id]||0)})).filter(x=>x.cantidad>0);if(!lineas.length)return mostrarAvisoDialogo("Ingresa al menos una cantidad para entregar.","Entrega incompleta",true);if(!responsable.trim())return mostrarAvisoDialogo("Escribe quién recibe o es responsable de la entrega.","Falta el responsable",true);if(!fechaReal)return mostrarAvisoDialogo("Selecciona la fecha y hora real.","Falta la fecha",true);setGuardando(true);try{const archivos=[];for(const ev of evidencias){const prep=await supabase.rpc("preparar_evidencia_entrega_v112",{p_nombre_archivo:ev.file.name,p_mime_type:ev.file.type,p_tamano_bytes:ev.file.size,p_idempotency_key:ev.id});if(prep.error)throw prep.error;const path=(prep.data as{path:string}).path;const subida=await supabase.storage.from("contratos-entregas").upload(path,ev.file,{contentType:ev.file.type,upsert:false});if(subida.error&&!/already exists|duplicate/i.test(subida.error.message))throw subida.error;archivos.push({id:ev.id,tipo:ev.tipo})}const{data,error}=await supabase.rpc("registrar_entrega_contrato_v112",{p_contrato_id:detalle.contrato.id,p_lineas:lineas,p_archivos:archivos,p_fecha_entrega_real:new Date(fechaReal).toISOString(),p_responsable:responsable.trim(),p_observacion:observacion.trim()||null,p_idempotency_key:crypto.randomUUID()});if(error)throw error;const r=data as{tipo:string;total:number};setMensaje(`Entrega ${r.tipo} registrada: ${r.total} prenda(s).`);await abrir(detalle.contrato.id);await cargar()}catch(e){await mostrarAvisoDialogo(e instanceof Error?e.message:String(e),"No se pudo registrar la entrega",true)}finally{setGuardando(false)}}
 async function revertir(entrega:Entrega){const motivo=await pedirMotivoDialogo(`Explica por qué se revertirá la entrega #${entrega.secuencia}. Las cantidades volverán a quedar pendientes.`,10,"Motivo de reversión");if(!motivo)return;const{error}=await supabase.rpc("revertir_entrega_contrato_v112",{p_entrega_id:entrega.id,p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});if(error)return mostrarAvisoDialogo(error.message,"No se pudo revertir la entrega",true);setMensaje(`Entrega #${entrega.secuencia} revertida.`);if(detalle){await abrir(detalle.contrato.id);await cargar()}}
 async function verArchivo(archivo:Archivo){const ventana=window.open("","_blank"),{data,error}=await supabase.storage.from("contratos-entregas").createSignedUrl(archivo.storage_path,300);if(error){ventana?.close();return mostrarAvisoDialogo(error.message,"No se pudo abrir la evidencia",true)}if(ventana){ventana.opener=null;ventana.location.href=data.signedUrl}else await mostrarAvisoDialogo("El navegador bloqueó la nueva pestaña. Habilita ventanas emergentes para abrir la evidencia.","No se pudo abrir la evidencia")}
 const paginas=Math.max(1,Math.ceil(lista.total/POR_PAGINA));
 return <>
 <div className={brief?estilos.noPrint:undefined}>
  <header className={estilos.cabecera}><div><span className="eyebrow">VENTAS · v158</span><h1>{esVendedor?"Mis contratos":"Centro de contratos"}</h1><p>Consulta el brief completo, pagos, vendedor responsable y estado real de cada entrega.</p></div><button className="secondary" disabled={cargando} onClick={()=>void Promise.all([cargar(),cargarCatalogo()])}>{cargando?"Actualizando…":"Actualizar"}</button></header>
  {puedeAsignar&&<section className={`card ${estilos.asignacion}`}><div className={estilos.asignacionIntro}><span className="eyebrow">CONTRATOS IMPORTADOS</span><h2>Asignar contratos a sus vendedores</h2><p><strong>{catalogo.sin_asignar}</strong> contratos todavía no están vinculados a una cuenta. Elige el nombre del archivo anterior y el usuario real una sola vez.</p></div><div className={estilos.asignacionCampos}><div className="field"><label>Nombre que vino importado</label><select value={origen} onChange={e=>setOrigen(e.target.value)}><option value="">Seleccionar…</option>{catalogo.origenes.map(x=><option value={x.nombre} key={x.nombre}>{x.nombre} · {x.cantidad} contrato(s)</option>)}</select></div><span className={estilos.flecha}>→</span><div className="field"><label>Cuenta del vendedor</label><select value={vendedorDestino} onChange={e=>setVendedorDestino(e.target.value)}><option value="">Seleccionar…</option>{catalogo.vendedores.map(x=><option value={x.id} key={x.id}>{x.nombre} · {x.contratos} asignado(s)</option>)}</select></div><button disabled={asignando||!origen||!vendedorDestino} onClick={()=>void asignar()}>{asignando?"Asignando…":"Asignar todos"}</button></div></section>}
  <section className={`card ${estilos.filtros}`}><div className="field"><label>Buscar contrato</label><input value={buscar} onChange={e=>setBuscar(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setPagina(1);setAplicado(buscar)}}} placeholder="Número, cliente o vendedor"/></div>{puedeAsignar&&<label className={estilos.check}><input type="checkbox" checked={soloSinAsignar} onChange={e=>{setPagina(1);setSoloSinAsignar(e.target.checked)}}/> Solo sin usuario asignado</label>}<button onClick={()=>{setPagina(1);setAplicado(buscar)}}>Buscar</button></section>
  <section className="card"><div className="header-row"><div><h2 style={{margin:0}}>{esVendedor?"Contratos asignados a mí":"Contratos"}</h2><span className="conteo">{lista.total} resultado(s)</span></div></div>{cargando?<div className={estilos.vacio}>Cargando…</div>:<div className="tabla-scroll"><table><thead><tr><th>Contrato</th><th>Vendedor asignado</th><th>Entrega</th><th className="num">Pedido</th><th className="num">Pendiente</th><th className="num">Saldo</th><th></th></tr></thead><tbody>{lista.filas.map(x=><tr key={x.id}><td><div className={estilos.contrato}><button className={estilos.miniatura} onClick={()=>void abrir(x.id)}><ImagenMockup driveId={x.mockup_drive_id} url={x.mockup_url} ancho={600} alt={`Mockup ${x.numero}`} vacio={<span>Sin imagen</span>}/></button><div><strong>{x.numero}</strong><span>{x.cliente}</span><small>{x.estado} · {x.prioridad}</small></div></div></td><td>{x.vendedor_usuario?<><strong>{x.vendedor_usuario}</strong><small className={estilos.bloque}>Cuenta vinculada</small></>:<><strong className={estilos.sinAsignar}>Sin usuario</strong><small className={estilos.bloque}>Importado como: {x.vendedor||"Sin vendedor"}</small></>}</td><td>{fecha(x.fecha_entrega)}</td><td className="num">{x.total_prendas}</td><td className="num"><strong className={x.pendientes?estilos.pendiente:estilos.completo}>{x.pendientes}</strong></td><td className="num"><strong className={x.saldo>0?estilos.pendiente:estilos.completo}>{DINERO.format(x.saldo)}</strong></td><td><button disabled={cargandoDetalle===x.id} onClick={()=>void abrir(x.id)}>{cargandoDetalle===x.id?"Abriendo…":"Abrir ficha"}</button></td></tr>)}{!lista.filas.length&&<tr><td colSpan={7} className={estilos.vacio}>No hay contratos con estos filtros.</td></tr>}</tbody></table></div>}{paginas>1&&<div className={estilos.paginacion}><button className="secondary" disabled={pagina===1} onClick={()=>setPagina(x=>x-1)}>Anterior</button><span>Página {pagina} de {paginas}</span><button className="secondary" disabled={pagina===paginas} onClick={()=>setPagina(x=>x+1)}>Siguiente</button></div>}</section>
  {detalle&&<section id="detalle-entrega-v158" className={estilos.detalle}><div className={estilos.detalleCabecera}><div><span className="eyebrow">{detalle.contrato.numero}</span><h2>{detalle.contrato.cliente}</h2><p>{detalle.contrato.vendedor||"Sin vendedor"} · estado {detalle.contrato.estado}</p></div><div><button onClick={()=>setBrief(detalle.brief)}>Ver brief grande</button><button className="secondary" onClick={()=>setDetalle(null)}>Cerrar</button></div></div>{mensaje&&<div className="success-box">{mensaje}</div>}
   <section className={estilos.resumen}><article><span>Presupuesto</span><strong>{DINERO.format(detalle.finanzas.presupuesto)}</strong></article><article><span>Abonado</span><strong>{DINERO.format(detalle.finanzas.abonado)}</strong></article><article className={detalle.finanzas.saldo>0?estilos.resumenAlerta:""}><span>Saldo pendiente</span><strong>{DINERO.format(detalle.finanzas.saldo)}</strong></article><article><span>Despacho</span><strong>{detalle.lineas.reduce((n,x)=>n+x.entregadas,0)} / {detalle.lineas.reduce((n,x)=>n+x.ordenadas,0)}</strong></article></section>
   {puedeAsignar&&<section className={`card ${estilos.reasignar}`}><div><h3>Vendedor responsable</h3><p>{detalle.finanzas.vendedor_usuario?`Actualmente asignado a ${detalle.finanzas.vendedor_usuario}.`:"Este contrato todavía no aparece en la cuenta de ningún vendedor."}</p></div><select value={vendedorDetalle} onChange={e=>setVendedorDetalle(e.target.value)}><option value="">Seleccionar vendedor…</option>{catalogo.vendedores.map(x=><option value={x.id} key={x.id}>{x.nombre}</option>)}</select><button disabled={asignando||!vendedorDetalle||vendedorDetalle===detalle.finanzas.vendedor_perfil_id} onClick={()=>void asignar(detalle.contrato.id)}>{asignando?"Guardando…":detalle.finanzas.vendedor_perfil_id?"Reasignar":"Asignar"}</button></section>}
   <section className="card"><div className="header-row"><div><h3 style={{margin:0}}>Abonos del contrato</h3><span className="conteo">Fecha real del pago y fecha de registro.</span></div></div><div className="tabla-scroll"><table><thead><tr><th>Fecha del pago</th><th>Medio</th><th>Referencia / nota</th><th>Registrado por</th><th className="num">Monto</th><th>Estado</th></tr></thead><tbody>{detalle.abonos.map(a=><tr key={a.id}><td><strong>{fecha(a.fecha)}</strong><small className={estilos.bloque}>Registrado {fechaHora(a.created_at)}</small></td><td>{a.medio_pago}</td><td>{a.referencia||a.nota||"—"}</td><td>{a.creado_por||"Sistema"}</td><td className="num"><strong>{DINERO.format(a.monto)}</strong></td><td><span className="badge ok">{a.estado}</span></td></tr>)}{!detalle.abonos.length&&<tr><td colSpan={6} className={estilos.vacio}>No hay movimientos de abono detallados. Si el contrato vino importado, el total inicial aparece arriba.</td></tr>}</tbody></table></div></section>
   {puedeEntregar&&detalle.lineas.some(x=>x.pendientes>0)&&<section className="card"><div className="header-row"><div><h3 style={{margin:0}}>Nueva entrega</h3><span className="conteo">Solo puedes entregar el saldo pendiente.</span></div><button className="secondary" onClick={completar}>Completar pendientes</button></div><div className="tabla-scroll"><table><thead><tr><th>Prenda</th><th>Variante</th><th className="num">Pedido</th><th className="num">Entregado</th><th className="num">Entregar ahora</th></tr></thead><tbody>{detalle.lineas.map(x=><tr key={x.id}><td><strong>{x.prenda}</strong><small className={estilos.bloque}>{x.calidad||"Sin calidad"}{x.detalle?` · ${x.detalle}`:""}</small></td><td>{x.genero} · {x.talla}</td><td className="num">{x.ordenadas}</td><td className="num">{x.entregadas}</td><td className="num"><input className={estilos.cantidad} type="number" min={0} max={x.pendientes} step={1} disabled={!x.pendientes} value={cantidades[x.id]||""} onChange={e=>setCantidades(v=>({...v,[x.id]:e.target.value}))} placeholder={String(x.pendientes)}/></td></tr>)}</tbody></table></div><div className={estilos.form}><div className="field"><label>Fecha y hora real *</label><input type="datetime-local" value={fechaReal} max={ahoraLocal()} onChange={e=>setFechaReal(e.target.value)}/></div><div className="field"><label>Responsable / recibe *</label><input value={responsable} onChange={e=>setResponsable(e.target.value)}/></div><div className={`field ${estilos.ancho}`}><label>Observación</label><textarea rows={2} value={observacion} onChange={e=>setObservacion(e.target.value)}/></div></div><div className={estilos.evidencias}><div><strong>Foto, firma o comprobante</strong><small>JPG, PNG, WebP o PDF · máximo 12 MB por archivo.</small></div><label className={estilos.archivoBoton}>+ Agregar evidencia<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{void agregar(e.target.files);e.target.value=""}}/></label></div>{evidencias.map(ev=><div className={estilos.evidenciaLocal} key={ev.id}><span>{ev.file.name}</span><select value={ev.tipo} onChange={e=>setEvidencias(xs=>xs.map(x=>x.id===ev.id?{...x,tipo:e.target.value as Evidencia["tipo"]}:x))}><option value="foto">Foto</option><option value="firma">Firma</option><option value="comprobante">Comprobante</option></select><button className="secondary btn-mini" onClick={()=>setEvidencias(xs=>xs.filter(x=>x.id!==ev.id))}>Quitar</button></div>)}<div className={estilos.acciones}><button disabled={guardando} onClick={()=>void guardar()}>{guardando?"Registrando…":"Registrar entrega"}</button></div></section>}
   <section className="card"><h3>Historial de entregas</h3><div className={estilos.historial}>{detalle.entregas.map(e=><article className={e.estado==="revertida"?estilos.revertida:""} key={e.id}><div><strong>Entrega #{e.secuencia} · {e.tipo}</strong><span>{e.total} prendas · {fechaHora(e.fecha_entrega_real)}</span><small>Responsable: {e.responsable} · registrada por {e.creado_por}</small>{e.observacion&&<p>{e.observacion}</p>}{e.estado==="revertida"&&<p><b>Revertida:</b> {e.motivo_reversion} · {e.revertido_por}</p>}</div><div className={estilos.historialAcciones}>{e.archivos.map(a=><button className="secondary btn-mini" key={a.id} onClick={()=>void verArchivo(a)}>{a.tipo}: {a.nombre_archivo}</button>)}{puedeRevertir&&e.estado==="aplicada"&&<button className="danger btn-mini" onClick={()=>void revertir(e)}>Revertir</button>}</div></article>)}{!detalle.entregas.length&&<div className={estilos.vacio}>Todavía no hay entregas registradas.</div>}</div></section>
  </section>}
 </div>
 {brief&&<div className={estilos.modal} role="dialog" aria-modal="true" aria-label={`Brief ${brief.contrato.numero}`}><div className={estilos.modalCuerpo}><div className={`${estilos.modalBarra} ${estilos.noPrint}`}><div><strong>{brief.contrato.numero}</strong><span>{brief.contrato.cliente}</span></div><div><button className="secondary" onClick={()=>window.print()}>Imprimir</button><button onClick={()=>setBrief(null)}>Cerrar</button></div></div><ExpedienteContrato datos={brief}/></div></div>}
 </>;
}
