"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useRef,useState}from"react";
import{mostrarAvisoDialogo,pedirMotivoDialogo}from"@/components/Dialogo";
import{createClient}from"@/lib/supabase/client";
import estilos from"./Entregas.module.css";

type Fila={id:string;numero:string;cliente:string;vendedor:string;estado:string;prioridad:string;fecha_entrega:string|null;total_prendas:number;entregadas:number;pendientes:number;mockup_drive_id:string|null;mockup_url:string|null};
type Lista={total:number;pagina:number;por_pagina:number;filas:Fila[]};
type Linea={id:string;prenda:string;calidad:string;detalle:string;genero:string;talla:string;ordenadas:number;entregadas:number;pendientes:number};
type Archivo={id:string;tipo:"foto"|"firma"|"comprobante";storage_path:string;nombre_archivo:string;mime_type:string};
type Entrega={id:string;secuencia:number;tipo:"parcial"|"completa";estado:"aplicada"|"revertida";fecha_entrega_real:string;responsable:string;observacion:string|null;creado_por:string;created_at:string;revertido_por:string|null;revertido_en:string|null;motivo_reversion:string|null;total:number;archivos:Archivo[]};
type Detalle={contrato:{id:string;numero:string;cliente:string;vendedor:string;estado:string;fecha_entrega:string|null;total_prendas:number};lineas:Linea[];entregas:Entrega[]};
type Evidencia={id:string;file:File;tipo:"foto"|"firma"|"comprobante"};
const VACIA:Lista={total:0,pagina:1,por_pagina:30,filas:[]},POR=30;
function fecha(v:string|null){return v?new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${v.slice(0,10)}T12:00:00Z`)):"—"}
function fechaHora(v:string){return new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Guayaquil"}).format(new Date(v))}
function ahoraLocal(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)}
function foto(x:Fila){return x.mockup_drive_id?`https://drive.google.com/thumbnail?id=${x.mockup_drive_id}&sz=w300`:x.mockup_url||""}

export default function EntregasCliente({nombre,puedeEntregar,puedeRevertir}:{nombre:string;puedeEntregar:boolean;puedeRevertir:boolean}){
 const supabase=useRef(createClient()).current;const[lista,setLista]=useState<Lista>(VACIA);const[buscar,setBuscar]=useState("");const[aplicado,setAplicado]=useState("");const[pagina,setPagina]=useState(1);const[cargando,setCargando]=useState(true);const[detalle,setDetalle]=useState<Detalle|null>(null);const[cargandoDetalle,setCargandoDetalle]=useState(false);const[cantidades,setCantidades]=useState<Record<string,string>>({});const[responsable,setResponsable]=useState(nombre);const[fechaReal,setFechaReal]=useState(ahoraLocal());const[observacion,setObservacion]=useState("");const[evidencias,setEvidencias]=useState<Evidencia[]>([]);const[guardando,setGuardando]=useState(false);const[mensaje,setMensaje]=useState("");
 const cargar=useCallback(async()=>{setCargando(true);const{data,error}=await supabase.rpc("listar_despachos_v112",{p_busqueda:aplicado||null,p_pagina:pagina,p_por_pagina:POR});setCargando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudieron cargar los contratos",true);setLista(data as Lista)},[aplicado,pagina,supabase]);
 useEffect(()=>{void cargar()},[cargar]);
 async function abrir(id:string){setCargandoDetalle(true);const{data,error}=await supabase.rpc("obtener_despacho_contrato_v112",{p_contrato_id:id});setCargandoDetalle(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo abrir el despacho",true);setDetalle(data as Detalle);setCantidades({});setEvidencias([]);setResponsable(nombre);setFechaReal(ahoraLocal());setObservacion("");setMensaje("");setTimeout(()=>document.getElementById("detalle-entrega-v112")?.scrollIntoView({behavior:"smooth"}),40)}
 function completar(){if(!detalle)return;setCantidades(Object.fromEntries(detalle.lineas.filter(x=>x.pendientes>0).map(x=>[x.id,String(x.pendientes)])))}
 async function agregar(files:FileList|null){if(!files)return;const permitidos=["image/jpeg","image/png","image/webp","application/pdf"],nuevos:Evidencia[]=[];for(const f of Array.from(files)){if(!permitidos.includes(f.type)||f.size<=0||f.size>12582912){await mostrarAvisoDialogo(`${f.name}: usa JPG, PNG, WebP o PDF de máximo 12 MB.`,"Evidencia no válida",true);continue}nuevos.push({id:crypto.randomUUID(),file:f,tipo:f.type==="application/pdf"?"comprobante":"foto"})}setEvidencias(x=>[...x,...nuevos])}
 async function guardar(){if(!detalle)return;const lineas=detalle.lineas.map(x=>({contrato_prenda_id:x.id,cantidad:Number(cantidades[x.id]||0)})).filter(x=>x.cantidad>0);if(!lineas.length)return mostrarAvisoDialogo("Ingresa al menos una cantidad para entregar.","Entrega incompleta",true);if(!responsable.trim())return mostrarAvisoDialogo("Escribe quién recibe o es responsable de la entrega.","Falta el responsable",true);if(!fechaReal)return mostrarAvisoDialogo("Selecciona la fecha y hora real.","Falta la fecha",true);setGuardando(true);try{const archivos=[];for(const ev of evidencias){const prep=await supabase.rpc("preparar_evidencia_entrega_v112",{p_nombre_archivo:ev.file.name,p_mime_type:ev.file.type,p_tamano_bytes:ev.file.size,p_idempotency_key:ev.id});if(prep.error)throw prep.error;const path=(prep.data as{path:string}).path;const subida=await supabase.storage.from("contratos-entregas").upload(path,ev.file,{contentType:ev.file.type,upsert:false});if(subida.error&&!/already exists|duplicate/i.test(subida.error.message))throw subida.error;archivos.push({id:ev.id,tipo:ev.tipo})}const{data,error}=await supabase.rpc("registrar_entrega_contrato_v112",{p_contrato_id:detalle.contrato.id,p_lineas:lineas,p_archivos:archivos,p_fecha_entrega_real:new Date(fechaReal).toISOString(),p_responsable:responsable.trim(),p_observacion:observacion.trim()||null,p_idempotency_key:crypto.randomUUID()});if(error)throw error;const r=data as{tipo:string;total:number};setMensaje(`Entrega ${r.tipo} registrada: ${r.total} prenda(s).`);await abrir(detalle.contrato.id);await cargar()}catch(e){await mostrarAvisoDialogo(e instanceof Error?e.message:String(e),"No se pudo registrar la entrega",true)}finally{setGuardando(false)}}
 async function revertir(e:Entrega){const motivo=await pedirMotivoDialogo(`Explica por qué se revertirá la entrega #${e.secuencia}. Las cantidades volverán a quedar pendientes.`,10,"Motivo de reversión");if(!motivo)return;const{error}=await supabase.rpc("revertir_entrega_contrato_v112",{p_entrega_id:e.id,p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});if(error)return mostrarAvisoDialogo(error.message,"No se pudo revertir la entrega",true);setMensaje(`Entrega #${e.secuencia} revertida.`);if(detalle){await abrir(detalle.contrato.id);await cargar()}}
 async function verArchivo(a:Archivo){const ventana=window.open("","_blank");const{data,error}=await supabase.storage.from("contratos-entregas").createSignedUrl(a.storage_path,300);if(error){ventana?.close();return mostrarAvisoDialogo(error.message,"No se pudo abrir la evidencia",true)}if(ventana){ventana.opener=null;ventana.location.href=data.signedUrl}else await mostrarAvisoDialogo("El navegador bloqueó la nueva pestaña. Habilita ventanas emergentes para abrir la evidencia.","No se pudo abrir la evidencia")}
 const paginas=Math.max(1,Math.ceil(lista.total/POR));
 return <><header className={estilos.cabecera}><div><span className="eyebrow">VENTAS · v112</span><h1>Despachos y entregas</h1><p>Entrega parcial o completa por prenda, responsable, evidencia y reversión auditada.</p></div></header>
 <section className={`card ${estilos.filtros}`}><div className="field"><label>Buscar contrato</label><input value={buscar}onChange={e=>setBuscar(e.target.value)}onKeyDown={e=>{if(e.key==="Enter"){setPagina(1);setAplicado(buscar)}}}placeholder="Número, cliente o vendedor"/></div><button onClick={()=>{setPagina(1);setAplicado(buscar)}}>Buscar</button></section>
 <section className="card"><div className="header-row"><div><h2 style={{margin:0}}>Contratos</h2><span className="conteo">{lista.total} resultado(s)</span></div></div>{cargando?<div className={estilos.vacio}>Cargando…</div>:<div className="tabla-scroll"><table><thead><tr><th>Contrato</th><th>Entrega</th><th className="num">Pedido</th><th className="num">Entregado</th><th className="num">Pendiente</th><th>Estado</th><th></th></tr></thead><tbody>{lista.filas.map(x=><tr key={x.id}><td><div className={estilos.contrato}>{foto(x)&&<img src={foto(x)}alt=""/>}<div><strong>{x.numero}</strong><span>{x.cliente}</span><small>{x.vendedor}</small></div></div></td><td>{fecha(x.fecha_entrega)}</td><td className="num">{x.total_prendas}</td><td className="num">{x.entregadas}</td><td className="num"><strong className={x.pendientes?estilos.pendiente:estilos.completo}>{x.pendientes}</strong></td><td><span className="badge ok">{x.estado}</span></td><td><button className="secondary"disabled={cargandoDetalle}onClick={()=>void abrir(x.id)}>Gestionar</button></td></tr>)}{!lista.filas.length&&<tr><td colSpan={7}className={estilos.vacio}>No hay contratos.</td></tr>}</tbody></table></div>}{paginas>1&&<div className={estilos.paginacion}><button className="secondary"disabled={pagina===1}onClick={()=>setPagina(x=>x-1)}>Anterior</button><span>{pagina} / {paginas}</span><button className="secondary"disabled={pagina===paginas}onClick={()=>setPagina(x=>x+1)}>Siguiente</button></div>}</section>
 {detalle&&<section id="detalle-entrega-v112"className={estilos.detalle}><div className={estilos.detalleCabecera}><div><span className="eyebrow">{detalle.contrato.numero}</span><h2>{detalle.contrato.cliente}</h2><p>{detalle.contrato.vendedor} · estado {detalle.contrato.estado}</p></div><button onClick={()=>setDetalle(null)}>Cerrar</button></div>{mensaje&&<div className="success-box">{mensaje}</div>}
 {puedeEntregar&&detalle.lineas.some(x=>x.pendientes>0)&&<section className="card"><div className="header-row"><div><h3 style={{margin:0}}>Nueva entrega</h3><span className="conteo">Solo puedes entregar el saldo pendiente.</span></div><button className="secondary"onClick={completar}>Completar pendientes</button></div><div className="tabla-scroll"><table><thead><tr><th>Prenda</th><th>Variante</th><th className="num">Pedido</th><th className="num">Entregado</th><th className="num">Entregar ahora</th></tr></thead><tbody>{detalle.lineas.map(x=><tr key={x.id}><td><strong>{x.prenda}</strong><small className={estilos.bloque}>{x.calidad||"Sin calidad"}{x.detalle?` · ${x.detalle}`:""}</small></td><td>{x.genero} · {x.talla}</td><td className="num">{x.ordenadas}</td><td className="num">{x.entregadas}</td><td className="num"><input className={estilos.cantidad}type="number"min={0}max={x.pendientes}step={1}disabled={!x.pendientes}value={cantidades[x.id]||""}onChange={e=>setCantidades(v=>({...v,[x.id]:e.target.value}))}placeholder={String(x.pendientes)}/></td></tr>)}</tbody></table></div><div className={estilos.form}><div className="field"><label>Fecha y hora real *</label><input type="datetime-local"value={fechaReal}max={ahoraLocal()}onChange={e=>setFechaReal(e.target.value)}/></div><div className="field"><label>Responsable / recibe *</label><input value={responsable}onChange={e=>setResponsable(e.target.value)}/></div><div className={`field ${estilos.ancho}`}><label>Observación</label><textarea rows={2}value={observacion}onChange={e=>setObservacion(e.target.value)}/></div></div><div className={estilos.evidencias}><div><strong>Foto, firma o comprobante</strong><small>JPG, PNG, WebP o PDF · máximo 12 MB por archivo.</small></div><label className={estilos.archivoBoton}>+ Agregar evidencia<input type="file"multiple accept="image/jpeg,image/png,image/webp,application/pdf"onChange={e=>{void agregar(e.target.files);e.target.value=""}}/></label></div>{evidencias.map(ev=><div className={estilos.evidenciaLocal}key={ev.id}><span>{ev.file.name}</span><select value={ev.tipo}onChange={e=>setEvidencias(xs=>xs.map(x=>x.id===ev.id?{...x,tipo:e.target.value as Evidencia["tipo"]}:x))}><option value="foto">Foto</option><option value="firma">Firma</option><option value="comprobante">Comprobante</option></select><button className="secondary btn-mini"onClick={()=>setEvidencias(xs=>xs.filter(x=>x.id!==ev.id))}>Quitar</button></div>)}<div className={estilos.acciones}><button disabled={guardando}onClick={()=>void guardar()}>{guardando?"Registrando…":"Registrar entrega"}</button></div></section>}
 <section className="card"><h3>Historial de entregas</h3><div className={estilos.historial}>{detalle.entregas.map(e=><article className={e.estado==="revertida"?estilos.revertida:""}key={e.id}><div><strong>Entrega #{e.secuencia} · {e.tipo}</strong><span>{e.total} prendas · {fechaHora(e.fecha_entrega_real)}</span><small>Responsable: {e.responsable} · registrada por {e.creado_por}</small>{e.observacion&&<p>{e.observacion}</p>}{e.estado==="revertida"&&<p><b>Revertida:</b> {e.motivo_reversion} · {e.revertido_por}</p>}</div><div className={estilos.historialAcciones}>{e.archivos.map(a=><button className="secondary btn-mini"key={a.id}onClick={()=>void verArchivo(a)}>{a.tipo}: {a.nombre_archivo}</button>)}{puedeRevertir&&e.estado==="aplicada"&&<button className="danger btn-mini"onClick={()=>void revertir(e)}>Revertir</button>}</div></article>)}{!detalle.entregas.length&&<div className={estilos.vacio}>Todavía no hay entregas registradas.</div>}</div></section></section>}
 </>;
}
