"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import { mensajeError } from "@/lib/errores";
import {confirmarDialogo,mostrarAvisoDialogo,pedirMotivoDialogo} from "@/components/Dialogo";
import {createClient} from "@/lib/supabase/client";
import estilos from "./CierreBomansport.module.css";

type Modo="paralelo"|"supabase_principal"|"cerrado";
type Checklist={respaldo_confirmado:boolean;paridad_confirmada:boolean;usuarios_validados:boolean;operacion_capacitada:boolean;apps_script_solo_lectura:boolean};
type Control={codigo:string;nombre:string;ok:boolean;bloqueante:boolean;detalle?:string};
type Diagnostico={configuracion:{modo:Modo;checklist:Checklist;supabase_principal_desde:string|null;cerrado_at:string|null;updated_at:string};metricas:{legacy_total:number;normalizados_total:number;coincidentes:number;legacy_sin_normalizar:number;contratos_invalidos:number;activos_sin_entrega:number};ultima_importacion:{estado:string;iniciado_en:string;con_error:number;mensaje_error:string|null}|null;controles:Control[];bloqueos:number};
const ETIQUETAS:Record<keyof Checklist,{titulo:string;detalle:string}>={respaldo_confirmado:{titulo:"Respaldo confirmado",detalle:"Existe una copia recuperable de Sheets y de Supabase."},paridad_confirmada:{titulo:"Paridad revisada",detalle:"Totales y una muestra de contratos coinciden en ambos sistemas."},usuarios_validados:{titulo:"Usuarios y permisos",detalle:"Cada área ingresó y validó únicamente sus funciones."},operacion_capacitada:{titulo:"Equipo capacitado",detalle:"Producción conoce el flujo nuevo y el procedimiento de contingencia."},apps_script_solo_lectura:{titulo:"Apps Script en solo lectura",detalle:"Nadie registra ni modifica contratos en la herramienta anterior."}};
function fecha(v:string|null|undefined){return v?new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Guayaquil"}).format(new Date(v)):"—"}

export default function CierreBomansportCliente(){
 const supabase=useRef(createClient()).current;const [datos,setDatos]=useState<Diagnostico|null>(null);const [checklist,setChecklist]=useState<Checklist|null>(null);const [cargando,setCargando]=useState(true);const [guardando,setGuardando]=useState(false);
 const cargar=useCallback(async()=>{setCargando(true);const{data,error}=await supabase.rpc("diagnostico_cierre_bomansport_v103");if(error)await mostrarAvisoDialogo(mensajeError(error, "v103_cierre_migracion_bomansport.sql"),"No se pudo evaluar la migración",true);else{const d=data as Diagnostico;setDatos(d);setChecklist(d.configuracion.checklist)}setCargando(false)},[supabase]);
 useEffect(()=>{void cargar()},[cargar]);
 async function guardar(modo:Modo){if(!datos||!checklist)return;if(modo!==datos.configuracion.modo&&!await confirmarDialogo(`Cambiarás la fuente operativa de “${datos.configuracion.modo}” a “${modo}”. ¿Deseas continuar?`,modo==="cerrado"))return;const motivo=await pedirMotivoDialogo(`Documenta por qué se guardará el checklist y el modo ${modo}.`,10,"Justificación del cambio");if(!motivo)return;setGuardando(true);const{error}=await supabase.rpc("admin_cambiar_cierre_bomansport_v103",{p_modo:modo,p_checklist:checklist,p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});setGuardando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo actualizar el cierre",true);await mostrarAvisoDialogo("El estado de migración quedó guardado y auditado.","Cambio aplicado");await cargar()}
 if(cargando&&!datos)return <div className="card"><div className={estilos.vacio}>Evaluando la migración…</div></div>;
 if(!datos||!checklist)return null;const m=datos.metricas;const todos=Object.values(checklist).every(Boolean);
 return <><header className={estilos.cabecera}><div><span className="eyebrow">ADMINISTRACIÓN · V103</span><h1>Cierre de migración BomanSport</h1><p>Transición segura desde Google Sheets y Apps Script hacia Supabase y Vercel, sin borrar el legado.</p></div><button className="secondary" onClick={cargar}>Volver a evaluar</button></header>
 <section className={estilos.estado}><div><span>Modo actual</span><strong>{datos.configuracion.modo.replace("_"," ")}</strong><small>Actualizado {fecha(datos.configuracion.updated_at)}</small></div><div className={datos.bloqueos?estilos.bloqueado:estilos.listo}><span>Diagnóstico</span><strong>{datos.bloqueos?`${datos.bloqueos} bloqueo(s)`:"Listo para transición"}</strong><small>La transición se bloquea si falta paridad.</small></div><div><span>Última importación</span><strong>{datos.ultima_importacion?.estado??"Sin corridas"}</strong><small>{fecha(datos.ultima_importacion?.iniciado_en)}</small></div></section>
 <div className={estilos.columnas}><section className="card"><h2>Controles automáticos</h2><div className={estilos.controles}>{datos.controles.map(c=><article key={c.codigo} className={c.ok?estilos.ok:estilos.fallo}><b>{c.ok?"✓":"!"}</b><div><strong>{c.nombre}</strong><small>{c.detalle}{c.bloqueante&&!c.ok?" · Bloquea el cierre":""}</small></div></article>)}</div><div className={estilos.metricas}><span><b>{m.legacy_total}</b> heredados</span><span><b>{m.normalizados_total}</b> normalizados</span><span><b>{m.coincidentes}</b> coincidentes</span><span><b>{m.legacy_sin_normalizar}</b> pendientes</span></div></section>
 <section className="card"><h2>Confirmación humana</h2><p className="conteo">Estas casillas no se completan automáticamente: el administrador responde por su validación.</p><div className={estilos.checklist}>{(Object.keys(ETIQUETAS) as Array<keyof Checklist>).map(k=><label key={k}><input type="checkbox" checked={checklist[k]} onChange={e=>setChecklist({...checklist,[k]:e.target.checked})}/><span><strong>{ETIQUETAS[k].titulo}</strong><small>{ETIQUETAS[k].detalle}</small></span></label>)}</div><button disabled={guardando} className="secondary" onClick={()=>guardar(datos.configuracion.modo)}>Guardar checklist</button></section></div>
 <section className="card"><h2>Transición operativa</h2><div className={estilos.flujo}><article className={datos.configuracion.modo==="paralelo"?estilos.activo:""}><span>1</span><div><strong>Paralelo</strong><small>La importación desde Apps Script continúa disponible.</small></div><button className="secondary" disabled={guardando||datos.configuracion.modo==="paralelo"} onClick={()=>guardar("paralelo")}>Volver a paralelo</button></article><i>→</i><article className={datos.configuracion.modo==="supabase_principal"?estilos.activo:""}><span>2</span><div><strong>Supabase principal</strong><small>Se bloquea la importación heredada; el legado queda consultable.</small></div><button disabled={guardando||datos.bloqueos>0||!todos||datos.configuracion.modo==="supabase_principal"||datos.configuracion.modo==="cerrado"} onClick={()=>guardar("supabase_principal")}>Activar</button></article><i>→</i><article className={datos.configuracion.modo==="cerrado"?estilos.activo:""}><span>3</span><div><strong>Cerrado</strong><small>Confirma el corte definitivo, conservando toda la auditoría.</small></div><button className="peligro" disabled={guardando||datos.configuracion.modo!=="supabase_principal"||datos.bloqueos>0||!todos} onClick={()=>guardar("cerrado")}>Cerrar migración</button></article></div><div className="info-box">El sistema nunca elimina la hoja ni sus archivos. Después de cerrar, las variables <code>BOMANSPORT_WEBAPP_URL</code> y <code>BOMANSPORT_API_TOKEN</code> se retiran manualmente de Vercel cuando el responsable confirme el respaldo.</div></section></>;
}
