"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { nuevaClaveIdempotencia } from "@/lib/erp";
import { dinero,hoyLocalISO,mensajeError } from "./lib";
import type { Franquicia } from "./FranquiciaCliente";
type Cuenta={id:string;cliente:string;identificacion:string|null;telefono:string|null;venta_numero:number|null;fecha:string;fecha_vencimiento:string;monto_original:number;saldo:number;estado:string;vencida:boolean};
export default function CarteraFranquicia({franquicia,soloLectura=false}:{franquicia:Franquicia;soloLectura?:boolean}){const supabase=useMemo(()=>createClient(),[]);const[cuentas,setCuentas]=useState<Cuenta[]>([]);const[cuenta,setCuenta]=useState("");const[monto,setMonto]=useState("");const[medio,setMedio]=useState("efectivo");const[ref,setRef]=useState("");const[error,setError]=useState<string|null>(null);const[procesando,setProcesando]=useState(false);
 async function cargar(){const{data,error}=await supabase.from("vista_cartera_franquicia_v81").select("*").eq("franquicia_id",franquicia.id).order("fecha_vencimiento");if(error)setError(error.message);else setCuentas((data??[])as Cuenta[]);}
 useEffect(()=>{cargar();},[franquicia.id]); const abiertas=cuentas.filter(c=>c.estado==="pendiente"); const saldo=abiertas.reduce((s,c)=>s+Number(c.saldo),0);
 async function cobrar(){const c=abiertas.find(x=>x.id===cuenta);if(!c||Number(monto)<=0)return setError("Selecciona una cuenta e indica el monto.");if(medio!=="efectivo"&&!ref.trim())return setError("La referencia es obligatoria para transferencia o tarjeta.");setProcesando(true);setError(null);const{error}=await supabase.rpc("registrar_cobro_franquicia_v81",{p_cuenta_id:c.id,p_fecha:hoyLocalISO(),p_monto:Number(monto),p_medio:medio,p_referencia:ref||null,p_idempotency_key:nuevaClaveIdempotencia()});setProcesando(false);if(error)return setError(mensajeError(error));setCuenta("");setMonto("");setRef("");await cargar();}
 return <><div className="kpis compactos"><div className="kpi"><span className="valor">{dinero(saldo)}</span><span className="label">Cartera pendiente</span></div><div className="kpi"><span className="valor">{abiertas.length}</span><span className="label">Cuentas abiertas</span></div><div className={`kpi ${abiertas.some(c=>c.vencida)?"alerta":""}`}><span className="valor">{abiertas.filter(c=>c.vencida).length}</span><span className="label">Vencidas</span></div></div>{error&&<p className="error">{error}</p>}{!soloLectura&&<div className="card-interna"><h4>Registrar abono</h4><div className="form-grid"><label>Cuenta<select value={cuenta} onChange={e=>{setCuenta(e.target.value);const c=abiertas.find(x=>x.id===e.target.value);setMonto(c?String(c.saldo):"");}}><option value="">Selecciona…</option>{abiertas.map(c=><option key={c.id} value={c.id}>{c.cliente} · saldo {dinero(c.saldo)}</option>)}</select></label><label>Monto<input type="number" min="0.01" step="0.01" value={monto} onChange={e=>setMonto(e.target.value)}/></label><label>Medio<select value={medio} onChange={e=>setMedio(e.target.value)}><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option></select></label>{medio!=="efectivo"&&<label>Referencia *<input value={ref} onChange={e=>setRef(e.target.value)}/></label>}</div><button onClick={cobrar} disabled={procesando}>Registrar abono</button></div>}<div className="tabla-scroll"><table><thead><tr><th>Cliente</th><th>Venta</th><th>Vence</th><th className="num">Original</th><th className="num">Saldo</th><th>Estado</th></tr></thead><tbody>{cuentas.map(c=><tr key={c.id} className={c.vencida?"fila-alerta":""}><td><strong>{c.cliente}</strong><small style={{display:"block"}}>{c.identificacion??c.telefono??""}</small></td><td>#{c.venta_numero??"XML"}</td><td>{c.fecha_vencimiento}</td><td className="num">{dinero(c.monto_original)}</td><td className="num">{dinero(c.saldo)}</td><td>{c.vencida?"vencida":c.estado}</td></tr>)}</tbody></table></div></>}
