"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { confirmarDialogo, mostrarAvisoDialogo, pedirMotivoDialogo } from "@/components/Dialogo";
import { createClient } from "@/lib/supabase/client";
import { mensajeError } from "@/lib/errores";
import estilos from "./CostosRentabilidad.module.css";

type Fila={id:string;numero:string;cliente:string;vendedor:string;estado:string;fecha_entrega:string|null;total_prendas:number;presupuesto:number;costo_estimado:number;costo_real:number;margen_estimado:number;margen_real:number;margen_real_pct:number|null;ordenes_pendientes:number};
type Kpis={ingresos:number;costo_estimado:number;costo_real:number;margen_estimado:number;margen_real:number;contratos_sin_costos:number;ordenes_sin_costo_real:number};
type Panel={total:number;pagina:number;por_pagina:number;kpis:Kpis;filas:Fila[];estados:string[]};
type Linea={id:string;naturaleza:"estimado"|"real";categoria:string;concepto:string;cantidad:number;costo_unitario:number;total:number;updated_at:string;usuario:string|null};
type Orden={id:string;numero:string;estado:string;resultado?:string;sku?:string;producto?:string;cantidad?:number;cantidad_planificada?:number;estimado?:number;costo_total_estimado?:number;real?:number|null};
type Hoja={contrato:{id:string;numero:string;cliente:string;estado:string;fecha_entrega:string|null;presupuesto:number;total_prendas:number};resumen:{manual_estimado:number;ordenes_estimado:number;costo_estimado:number;manual_real:number;ordenes_real:number;costo_real:number;margen_estimado:number;margen_real:number;margen_estimado_pct:number|null;margen_real_pct:number|null;ordenes_sin_costo_real:number};lineas:Linea[];ordenes:Orden[];ordenes_disponibles:Orden[]};

const DINERO=new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"});
const VACIO:Panel={total:0,pagina:1,por_pagina:40,kpis:{ingresos:0,costo_estimado:0,costo_real:0,margen_estimado:0,margen_real:0,contratos_sin_costos:0,ordenes_sin_costo_real:0},filas:[],estados:[]};
const FORM_VACIO={id:"",naturaleza:"estimado",categoria:"materiales",concepto:"",cantidad:"1",costo_unitario:""};
function isoLocal(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function fecha(v:string|null){return v?new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`)):"—"}
function csv(v:unknown){return `"${String(v??"").replaceAll('"','""')}"`}

export default function CostosRentabilidadCliente({puedeEditar}:{puedeEditar:boolean}){
 const ahora=new Date();const inicio=new Date(ahora.getFullYear(),ahora.getMonth(),1);const fin=new Date(ahora.getFullYear(),ahora.getMonth()+1,0);
 const supabase=useRef(createClient()).current;
 const [desde,setDesde]=useState(isoLocal(inicio));const [hasta,setHasta]=useState(isoLocal(fin));const [estado,setEstado]=useState("");const [busqueda,setBusqueda]=useState("");
 const [filtros,setFiltros]=useState({desde:isoLocal(inicio),hasta:isoLocal(fin),estado:"",busqueda:""});const [pagina,setPagina]=useState(1);const [panel,setPanel]=useState(VACIO);const [cargando,setCargando]=useState(true);const [hoja,setHoja]=useState<Hoja|null>(null);const [cargandoHoja,setCargandoHoja]=useState(false);const [form,setForm]=useState(FORM_VACIO);const [ordenId,setOrdenId]=useState("");const [procesando,setProcesando]=useState(false);
 const cargar=useCallback(async()=>{setCargando(true);const{data,error}=await supabase.rpc("dashboard_rentabilidad_v101",{p_desde:filtros.desde,p_hasta:filtros.hasta,p_estado:filtros.estado||null,p_busqueda:filtros.busqueda||null,p_pagina:pagina,p_por_pagina:40});if(error)await mostrarAvisoDialogo(mensajeError(error, "v101_costos_rentabilidad_contratos.sql"),"No se pudo cargar rentabilidad",true);else setPanel(data as Panel);setCargando(false)},[filtros,pagina,supabase]);
 useEffect(()=>{void cargar()},[cargar]);
 async function abrir(id:string){setCargandoHoja(true);const{data,error}=await supabase.rpc("obtener_hoja_costo_v101",{p_contrato_id:id});if(error)await mostrarAvisoDialogo(error.message,"No se pudo abrir la hoja",true);else{setHoja(data as Hoja);setForm(FORM_VACIO);setOrdenId("");setTimeout(()=>document.getElementById("hoja-costo-v101")?.scrollIntoView({behavior:"smooth",block:"start"}),40)}setCargandoHoja(false)}
 async function recargarHoja(){if(hoja)await abrir(hoja.contrato.id);await cargar()}
 async function guardarLinea(){if(!hoja)return;if(form.concepto.trim().length<3||Number(form.cantidad)<=0||Number(form.costo_unitario)<0||form.costo_unitario===""){await mostrarAvisoDialogo("Completa concepto, cantidad y costo unitario.","Datos incompletos",true);return}const motivo=await pedirMotivoDialogo(`${form.id?"Editarás":"Agregarás"} una línea ${form.naturaleza} a ${hoja.contrato.numero}.`,10,"Motivo del costo");if(!motivo)return;setProcesando(true);const{error}=await supabase.rpc("guardar_costo_contrato_v101",{p_contrato_id:hoja.contrato.id,p_linea_id:form.id||null,p_naturaleza:form.naturaleza,p_categoria:form.categoria,p_concepto:form.concepto,p_cantidad:Number(form.cantidad),p_costo_unitario:Number(form.costo_unitario),p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});setProcesando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo guardar",true);await recargarHoja()}
 async function anular(linea:Linea){if(!await confirmarDialogo(`Se anulará ${linea.concepto} por ${DINERO.format(linea.total)}. ¿Continuar?`,true))return;const motivo=await pedirMotivoDialogo("Explica por qué se anula esta línea de costo.",10);if(!motivo)return;setProcesando(true);const{error}=await supabase.rpc("anular_costo_contrato_v101",{p_linea_id:linea.id,p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});setProcesando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo anular",true);await recargarHoja()}
 async function vincular(orden:Orden,vincular:boolean){if(!hoja)return;const motivo=await pedirMotivoDialogo(`${vincular?"Vincularás":"Desvincularás"} la orden ${orden.numero} ${vincular?"a":"de"} ${hoja.contrato.numero}.`,10);if(!motivo)return;setProcesando(true);const{error}=await supabase.rpc("vincular_orden_costo_v101",{p_contrato_id:hoja.contrato.id,p_orden_id:orden.id,p_vincular:vincular,p_motivo:motivo,p_idempotency_key:crypto.randomUUID()});setProcesando(false);if(error)return mostrarAvisoDialogo(error.message,"No se pudo actualizar el vínculo",true);await recargarHoja()}
 function exportar(){const encabezado=["Contrato","Cliente","Estado","Entrega","Presupuesto","Costo estimado","Costo real","Margen estimado","Margen real","Margen real %"];const filas=panel.filas.map(x=>[x.numero,x.cliente,x.estado,x.fecha_entrega,x.presupuesto,x.costo_estimado,x.costo_real,x.margen_estimado,x.margen_real,x.margen_real_pct]);const contenido=[encabezado,...filas].map(r=>r.map(csv).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+contenido],{type:"text/csv;charset=utf-8"}));a.download=`rentabilidad_${filtros.desde}_${filtros.hasta}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const totalPag=Math.max(1,Math.ceil(panel.total/40));const k=panel.kpis;
 return <>
  <header className={estilos.cabecera}><div><span className="eyebrow">PRODUCCIÓN · FINANZAS</span><h1>Costos y rentabilidad</h1><p>Compara presupuesto, costo estimado y costo real. Las órdenes vinculadas se actualizan automáticamente; los adicionales quedan auditados.</p></div><button className="secondary" onClick={exportar} disabled={!panel.filas.length}>Exportar página</button></header>
  <section className={`card ${estilos.filtros}`}><div className="field"><label>Desde</label><input type="date" value={desde} onChange={e=>setDesde(e.target.value)}/></div><div className="field"><label>Hasta</label><input type="date" value={hasta} onChange={e=>setHasta(e.target.value)}/></div><div className="field"><label>Estado</label><select value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos</option>{panel.estados.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Contrato o cliente</label><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setPagina(1);setFiltros({desde,hasta,estado,busqueda})}}} placeholder="Buscar…"/></div><button onClick={()=>{setPagina(1);setFiltros({desde,hasta,estado,busqueda})}}>Actualizar</button></section>
  <section className={estilos.kpis}><article><span>Ingresos contratados</span><strong>{DINERO.format(k.ingresos)}</strong><small>{panel.total} contrato(s)</small></article><article><span>Costo estimado</span><strong>{DINERO.format(k.costo_estimado)}</strong><small>órdenes + hoja manual</small></article><article><span>Costo real</span><strong>{DINERO.format(k.costo_real)}</strong><small>{k.ordenes_sin_costo_real} orden(es) por cerrar</small></article><article className={k.margen_real<0?estilos.negativo:estilos.positivo}><span>Margen real</span><strong>{DINERO.format(k.margen_real)}</strong><small>sobre valor contratado</small></article><article className={k.contratos_sin_costos?estilos.alerta:""}><span>Sin hoja de costo</span><strong>{k.contratos_sin_costos}</strong><small>requieren revisión</small></article></section>
  <section className="card"><div className="header-row"><h2 style={{margin:0}}>Rentabilidad por contrato</h2><span className="conteo">Página {pagina} de {totalPag}</span></div>{cargando?<div className={estilos.vacio}>Calculando rentabilidad…</div>:<div className="tabla-scroll"><table><thead><tr><th>Contrato</th><th>Estado / entrega</th><th className="num">Ingreso</th><th className="num">Estimado</th><th className="num">Real</th><th className="num">Margen real</th><th></th></tr></thead><tbody>{panel.filas.map(x=><tr key={x.id} className={x.margen_real<0?estilos.filaNegativa:""}><td><strong>{x.numero}</strong><div>{x.cliente}</div><small>{x.total_prendas} prendas · {x.vendedor||"Sin vendedor"}</small></td><td><span className="badge ok">{x.estado}</span><div>{fecha(x.fecha_entrega)}</div>{x.ordenes_pendientes>0&&<small className={estilos.advertencia}>{x.ordenes_pendientes} orden(es) sin costo real</small>}</td><td className="num">{DINERO.format(x.presupuesto)}</td><td className="num">{DINERO.format(x.costo_estimado)}</td><td className="num">{DINERO.format(x.costo_real)}</td><td className={`num ${x.margen_real<0?estilos.textoNegativo:estilos.textoPositivo}`}><strong>{DINERO.format(x.margen_real)}</strong><div>{x.margen_real_pct==null?"—":`${x.margen_real_pct}%`}</div></td><td><button className="secondary" disabled={cargandoHoja} onClick={()=>abrir(x.id)}>Hoja de costo</button></td></tr>)}{!panel.filas.length&&<tr><td colSpan={7} className={estilos.vacio}>No hay contratos en este rango.</td></tr>}</tbody></table></div>}{totalPag>1&&<div className={estilos.paginacion}><button className="secondary" disabled={pagina===1} onClick={()=>setPagina(x=>x-1)}>Anterior</button><span>Página {pagina} de {totalPag}</span><button className="secondary" disabled={pagina===totalPag} onClick={()=>setPagina(x=>x+1)}>Siguiente</button></div>}</section>
  {hoja&&<section id="hoja-costo-v101" className={estilos.hoja}><div className={estilos.hojaCabecera}><div><span className="eyebrow">HOJA DE COSTO</span><h2>{hoja.contrato.numero} · {hoja.contrato.cliente}</h2><p>{hoja.contrato.total_prendas} prendas · presupuesto {DINERO.format(hoja.contrato.presupuesto)}</p></div><button className="secondary" onClick={()=>setHoja(null)}>Cerrar hoja</button></div>
   <div className={estilos.resumen}><article><span>Estimado</span><strong>{DINERO.format(hoja.resumen.costo_estimado)}</strong><small>margen {DINERO.format(hoja.resumen.margen_estimado)} · {hoja.resumen.margen_estimado_pct??"—"}%</small></article><article><span>Real</span><strong>{DINERO.format(hoja.resumen.costo_real)}</strong><small>margen {DINERO.format(hoja.resumen.margen_real)} · {hoja.resumen.margen_real_pct??"—"}%</small></article><article><span>Origen automático</span><strong>{DINERO.format(hoja.resumen.ordenes_real)}</strong><small>{hoja.ordenes.length} orden(es) vinculadas</small></article></div>
   {puedeEditar&&<section className="card"><h3>{form.id?"Editar línea":"Agregar costo manual"}</h3><div className={estilos.formulario}><div className="field"><label>Tipo</label><select value={form.naturaleza} onChange={e=>setForm({...form,naturaleza:e.target.value})}><option value="estimado">Estimado</option><option value="real">Real</option></select></div><div className="field"><label>Categoría</label><select value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}>{["materiales","mano_obra","maquila","indirectos","transporte","otros"].map(x=><option value={x} key={x}>{x.replace("_"," ")}</option>)}</select></div><div className="field"><label>Concepto</label><input value={form.concepto} onChange={e=>setForm({...form,concepto:e.target.value})} placeholder="Ej. Bordado adicional"/></div><div className="field"><label>Cantidad</label><input type="number" min="0.0001" step="0.0001" value={form.cantidad} onChange={e=>setForm({...form,cantidad:e.target.value})}/></div><div className="field"><label>Costo unitario</label><input type="number" min="0" step="0.000001" value={form.costo_unitario} onChange={e=>setForm({...form,costo_unitario:e.target.value})}/></div><div className={estilos.acciones}><button disabled={procesando} onClick={guardarLinea}>{form.id?"Guardar edición":"Agregar línea"}</button>{form.id&&<button className="secondary" onClick={()=>setForm(FORM_VACIO)}>Cancelar</button>}</div></div></section>}
   <div className={estilos.columnas}><section className="card"><h3>Costos manuales</h3><div className="tabla-scroll"><table><thead><tr><th>Tipo / categoría</th><th>Concepto</th><th className="num">Cantidad</th><th className="num">Unitario</th><th className="num">Total</th>{puedeEditar&&<th/>}</tr></thead><tbody>{hoja.lineas.map(l=><tr key={l.id}><td><span className={`badge ${l.naturaleza==="real"?"ok":"cero"}`}>{l.naturaleza}</span><div>{l.categoria.replace("_"," ")}</div></td><td>{l.concepto}<small style={{display:"block"}}>por {l.usuario||"usuario"}</small></td><td className="num">{l.cantidad}</td><td className="num">{DINERO.format(l.costo_unitario)}</td><td className="num"><strong>{DINERO.format(l.total)}</strong></td>{puedeEditar&&<td><div className={estilos.acciones}><button className="secondary btn-mini" onClick={()=>setForm({id:l.id,naturaleza:l.naturaleza,categoria:l.categoria,concepto:l.concepto,cantidad:String(l.cantidad),costo_unitario:String(l.costo_unitario)})}>Editar</button><button className="peligro btn-mini" onClick={()=>anular(l)}>Anular</button></div></td>}</tr>)}{!hoja.lineas.length&&<tr><td colSpan={6} className={estilos.vacio}>Sin costos manuales.</td></tr>}</tbody></table></div></section>
   <section className="card"><h3>Órdenes de producción</h3>{puedeEditar&&<div className={estilos.vincular}><select value={ordenId} onChange={e=>setOrdenId(e.target.value)}><option value="">Seleccionar orden disponible…</option>{hoja.ordenes_disponibles.map(o=><option key={o.id} value={o.id}>{o.numero} · {o.sku} · {o.producto}</option>)}</select><button disabled={!ordenId||procesando} onClick={()=>{const o=hoja.ordenes_disponibles.find(x=>x.id===ordenId);if(o)void vincular(o,true)}}>Vincular</button></div>}<div className={estilos.ordenes}>{hoja.ordenes.map(o=><article key={o.id}><div><strong>{o.numero}</strong><span>{o.resultado}</span><small>{o.estado} · {o.cantidad} unidades</small></div><div className={estilos.ordenValores}><span>Est. <b>{DINERO.format(Number(o.estimado||0))}</b></span><span>Real <b>{o.real==null?"Pendiente":DINERO.format(Number(o.real))}</b></span>{puedeEditar&&<button className="secondary btn-mini" onClick={()=>vincular(o,false)}>Desvincular</button>}</div></article>)}{!hoja.ordenes.length&&<div className={estilos.vacio}>No hay órdenes vinculadas.</div>}</div></section></div>
  </section>}
 </>;
}
